const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../src/materials'),W=require('../src/workspaces'),B=require('../src/brush'),{parseABR}=require('../src/abr'),{DrawingStore}=require('../src/storage');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
function abr(version=2,rle=false,depth=8){const u16=n=>{const b=Buffer.alloc(2);b.writeUInt16BE(n);return b;},u32=n=>{const b=Buffer.alloc(4);b.writeUInt32BE(n);return b;},name=Buffer.from([0,65,0,0]);const pix=rle?Buffer.from([0,3,0,3,1,0,255,1,255,0]):Buffer.from([0,255,255,0]);const image=Buffer.concat([u32(0),u32(0),u32(2),u32(2),u16(depth),Buffer.from([rle?1:0]),pix]);if(version===1||version===2){const record=Buffer.concat([u32(0),u16(20),...(version===2?[u32(2),name]:[]),Buffer.alloc(9),image]);return Buffer.concat([u16(version),u16(1),u16(2),u32(record.length),record]);}const record=Buffer.concat([Buffer.alloc(47),image]),samp=Buffer.concat([u32(record.length),record,Buffer.alloc((4-record.length%4)%4)]);return Buffer.concat([u16(version),u16(1),Buffer.from('8BIMsamp'),u32(samp.length),samp]);}
test('ABR 1/2/6/10 raw and PackBits sampled records convert; unsupported depth and truncation report without throwing',()=>{for(const v of [1,2,6,10])for(const rle of [false,true]){const r=parseABR(abr(v,rle));assert.equal(r.brushes.length,1);assert.deepEqual([...Buffer.from(r.brushes[0].asset.mask,'base64')],[0,255,255,0]);assert.equal(r.skipped.length,0);}assert.match(parseABR(abr(2,false,16)).skipped[0],/16비트/);assert.equal(parseABR(abr().subarray(0,20)).brushes.length,0);assert.ok(parseABR(Buffer.from([0,99,0,0])).skipped.length);});
test('Six multi-tip orders are bounded and deterministic',()=>{const seq=mode=>Array.from({length:7},(_,i)=>M.tipIndex(i,3,mode));assert.deepEqual(seq('repeat'),[0,1,2,0,1,2,0]);assert.deepEqual(seq('reverse'),[0,1,2,1,0,1,2]);assert.deepEqual(seq('last'),[0,1,2,2,2,2,2]);assert.deepEqual(seq('once'),[0,1,2,-1,-1,-1,-1]);const r=seq('random-once');assert.equal(new Set(r.slice(0,3)).size,3);assert.deepEqual(r.slice(3),[-1,-1,-1,-1]);assert.deepEqual(seq('random'),seq('random'));});
test('Texture coverage preserves transparent boundaries, bounded output and height center',()=>{for(const[mode]of M.modes)for(const a of [0,.15,.5,1])for(const g of [0,.3,.8,1]){const out=M.coverage(a,g,1,mode);assert.ok(out>=0&&out<=1);if(!a)assert.equal(out,0);}assert.equal(M.coverage(1,.2,1,'height'),1);assert.notEqual(M.coverage(.3,.6,1,'dodge'),.3);assert.equal(M.coverage(.3,.6,0,'multiply'),.3);});
test('Workspace import adds isolated IDs, removes damaged assets, retains pressure/defaults and excludes artwork/device',()=>{const s=B.upgrade({color:'#112233',inputMode:'pen'});W.upgradeWorkspaces(s);s.presets[0].tips=[...s.library.filter(a=>a.kind==='tip')];s.presets[0].tipType='custom';s.presets[0].defaults={...s.presets[0].defaults,size:88};s.textStyle.background=true;s.layers=[{id:'foreign'}];W.captureCurrent(s);const payload={format:'canvas-drawing-workspace',version:1,workspace:s.workspaces[0]};payload.workspace.state.library.push({id:'bad'});const r=W.importWorkspaces(payload);assert.equal(r.workspaces.length,1);assert.ok(r.report.length);const state=r.workspaces[0].state;assert.notEqual(r.workspaces[0].id,s.workspaceId);assert.notEqual(state.presets[0].id,s.presets[0].id);assert.equal(state.presets[0].defaults.size,88);assert.equal(state.presets[0].sizeDynamics.enabled,true);assert.equal(state.textStyle.background,true);assert.equal(state.library.length,2);assert.equal(state.presets[0].tips.length,1);assert.ok(!('inputMode'in state)&&!('layers'in state));W.applyState(s,state);assert.equal(s.inputMode,'pen');assert.ok(s.shapeStyle.kind);});
test('Drawing v7 retains independent material pixels after library deletion and save/reopen',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'cdt-gate8-')),store=new DrawingStore(root),id=randomUUID(),r=store.load(id,'test.canvas');const layer=require('../src/layers').makeLayer();const p=B.preset('p','test','brush',{tipType:'custom',tips:[M.builtins()[0]]});Object.assign(r.data,{version:7,assets:{},layers:[layer],selectedLayers:[layer.id]});const stroke={...M.freezeMaterials(p,r.data),id:randomUUID(),layerId:layer.id,color:'#112233',points:[[0,0,1,1,1,0]]};r.data.strokes.push(stroke);store.changed(r);assert.equal(store.flush(r),true);p.tips=[];const loaded=new DrawingStore(root).load(id,'test.canvas',true).data;assert.equal(loaded.assets[loaded.strokes[0].tips[0]].mask,M.builtins()[0].mask);const old=loaded.assets[loaded.strokes[0].tips[0]];old.mask='bad';assert.throws(()=>require('../src/storage').encode(loaded));fs.rmSync(root,{recursive:true,force:true});});
module.exports={abr};
test('v6 upgrade keeps exact pre-upgrade bytes alongside material-aware v7 document',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'cdt-upgrade7-')),store=new DrawingStore(root),id=randomUUID(),r=store.load(id,'old.canvas');Object.assign(r.data,{version:6,layers:[],selectedLayers:[]});store.changed(r);assert.ok(store.flush(r));const before=fs.readFileSync(store.file(id));r.data.version=7;r.data.assets={};store.changed(r);assert.ok(store.flush(r));assert.deepEqual(fs.readFileSync(store.file(id)+'.v6.bak'),before);assert.equal(new DrawingStore(root).load(id,'old.canvas').data.version,7);fs.rmSync(root,{recursive:true,force:true});});
test('Portable material catalog deduplicates copied workspaces while preserving names and damaged-entry salvage',()=>{const s=B.upgrade({color:'#112233'});W.upgradeWorkspaces(s);s.presets[0].tips=[s.library[0]];W.captureCurrent(s);const w=s.workspaces[0];const packet={format:'canvas-drawing-settings',version:1,workspaces:[w,{...B.clone(w),id:randomUUID()}]};const packed=M.packMaterials(packet);assert.equal(Object.keys(packed.materialCatalog).length,2);assert.deepEqual(M.unpackMaterials(packed),packet);delete packed.materialCatalog[s.library[0].id];const report=W.importWorkspaces(M.unpackMaterials(packed));assert.equal(report.workspaces.length,2);assert.ok(report.report.length>=2);assert.equal(report.workspaces[0].state.presets[0].tips.length,0);});
