const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {DrawingStore,decode,randomUUID}=require('../src/storage');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'canvas-drawing-gate1-'));t.after(()=>{const resolved=path.resolve(root);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep+'canvas-drawing-gate1-'));fs.rmSync(resolved,{recursive:true,force:true});});return {root,store:new DrawingStore(root)};}
function stroke(store,r,x=10){r.data.strokes.push({id:randomUUID(),size:12,color:'#b6a0e2',points:[[x,10],[x+20,30]]});store.changed(r);}
test('Canvas documents save independently and reload after a new store instance',t=>{const {root,store}=fixture(t),a=store.load(randomUUID(),'A.canvas'),b=store.load(randomUUID(),'B.canvas');stroke(store,a);stroke(store,b,80);assert.equal(store.writeCount,0);assert.equal(store.flushAll(),true);const next=new DrawingStore(root);assert.deepEqual(next.load(a.data.id,'A.canvas',true).data,a.data);assert.notDeepEqual(next.load(b.data.id,'B.canvas',true).data.strokes,a.data.strokes);});
test('the last known good version survives interrupted replacement and retry saves pending edits',t=>{const {store}=fixture(t),r=store.load(randomUUID(),'A.canvas');stroke(store,r);store.flush(r);const original=fs.readFileSync(store.file(r.data.id),'utf8');stroke(store,r);store.io=new Proxy(fs,{get(target,key){if(key==='renameSync')return(a,b)=>{if(b===store.file(r.data.id))throw Error('simulated write failure');return fs.renameSync(a,b);};return target[key];}});assert.equal(store.flush(r),false);assert.equal(r.dirty,true);assert.equal(fs.readFileSync(store.file(r.data.id),'utf8'),original);assert.equal(fs.readFileSync(store.file(r.data.id)+'.bak','utf8'),original);store.io=fs;assert.equal(store.flush(r),true);assert.equal(decode(fs.readFileSync(store.file(r.data.id),'utf8'),r.data.id).strokes.length,2);});
test('corrupted, missing and future-version data stay protected',t=>{const {root,store}=fixture(t),id=randomUUID();fs.mkdirSync(store.root,{recursive:true});fs.writeFileSync(store.file(id),'original broken bytes');assert.throws(()=>store.load(id,'A.canvas',true));assert.equal(fs.readFileSync(store.file(id),'utf8'),'original broken bytes');assert.throws(()=>store.load(randomUUID(),'missing.canvas',true));const r=store.load(randomUUID(),'future.canvas');stroke(store,r);store.flush(r);const f=store.file(r.data.id),envelope=JSON.parse(fs.readFileSync(f,'utf8')),payload=JSON.parse(envelope.payload);payload.version=99;envelope.payload=JSON.stringify(payload);envelope.checksum=require('node:crypto').createHash('sha256').update(envelope.payload).digest('hex');fs.writeFileSync(f,JSON.stringify(envelope));assert.throws(()=>new DrawingStore(root).load(r.data.id,'future.canvas',true));stroke(store,r);assert.equal(store.flush(r),false);assert.equal(JSON.parse(JSON.parse(fs.readFileSync(f,'utf8')).payload).version,99);});
test('stale external revision cannot overwrite another writer',t=>{const {root,store}=fixture(t),r=store.load(randomUUID(),'A.canvas');stroke(store,r);store.flush(r);const other=new DrawingStore(root),rr=other.load(r.data.id,'A.canvas',true);stroke(other,rr);other.flush(rr);stroke(store,r);assert.equal(store.flush(r),false);});
test('empty drawing after undo persists and path traversal is rejected',t=>{const {root,store}=fixture(t),r=store.load(randomUUID(),'A.canvas');stroke(store,r);store.flush(r);r.data.strokes=[];store.changed(r);assert.equal(store.flush(r),true);assert.deepEqual(new DrawingStore(root).load(r.data.id,'A.canvas',true).data.strokes,[]);assert.throws(()=>store.file('../outside'));});

test('Gate 2 upgrade retains v1 bytes and reloads brush and eraser operations',t=>{const {root,store}=fixture(t),r=store.load(randomUUID(),'upgrade.canvas');stroke(store,r);store.flush(r);const original=fs.readFileSync(store.file(r.data.id),'utf8');r.data.version=2;r.data.strokes.push({id:randomUUID(),tool:'eraser',color:'#000000',size:20,opacity:.5,density:1,hardness:.5,mix:false,paintAmount:.5,colorStretch:.5,points:[[15,15],[30,30]]});store.changed(r);assert.equal(store.flush(r),true);assert.equal(fs.readFileSync(store.file(r.data.id)+'.v1.bak','utf8'),original);const next=new DrawingStore(root).load(r.data.id,'upgrade.canvas',true);assert.deepEqual(next.data,r.data);stroke(store,r);store.flush(r);assert.equal(fs.readFileSync(store.file(r.data.id)+'.v1.bak','utf8'),original);});
test('invalid Gate 2 rendering parameters never replace the last valid file',t=>{const {store}=fixture(t),r=store.load(randomUUID(),'settings.canvas');stroke(store,r);store.flush(r);const original=fs.readFileSync(store.file(r.data.id),'utf8');r.data.version=2;r.data.strokes.push({id:randomUUID(),tool:'eraser',size:20,color:'#000000',opacity:2,density:1,hardness:1,mix:false,paintAmount:.5,colorStretch:.5,points:[[0,0]]});store.changed(r);assert.equal(store.flush(r),false);assert.equal(fs.readFileSync(store.file(r.data.id),'utf8'),original);});

test('Gate 3 pressure geometry reloads and preserves its pre-upgrade file',t=>{const {root,store}=fixture(t),r=store.load(randomUUID(),'pen.canvas');stroke(store,r);store.flush(r);const old=fs.readFileSync(store.file(r.data.id),'utf8');const preset=require('../src/brush').preset('p','pen','brush');r.data.version=3;r.data.strokes.push({...preset,id:randomUUID(),color:'#b6a0e2',points:[[0,0,.1,1,1,0],[30,20,1,.5,.3,45]]});store.changed(r);assert.equal(store.flush(r),true);assert.equal(fs.readFileSync(store.file(r.data.id)+'.v1.bak','utf8'),old);assert.deepEqual(new DrawingStore(root).load(r.data.id,'pen.canvas',true).data,r.data);const good=fs.readFileSync(store.file(r.data.id),'utf8');r.data.strokes.at(-1).particleCount=Infinity;store.changed(r);assert.equal(store.flush(r),false);assert.equal(fs.readFileSync(store.file(r.data.id),'utf8'),good);});
