"use strict";
const presets=[15,45,75,90];
function ensure(q){q.brushSnapEnabled=!!q.brushSnapEnabled;q.brushSnapAngle=Number.isFinite(q.brushSnapAngle)&&q.brushSnapAngle>=.1&&q.brushSnapAngle<=180?q.brushSnapAngle:45;q.brushSnapCustom=!!q.brushSnapCustom;}
function point(a,b,step){const dx=b[0]-a[0],dy=b[1]-a[1],r=Math.hypot(dx,dy),angle=(Math.atan2(dy,dx)*180/Math.PI+360)%360;let best=0,distance=Infinity;for(let k=0;k*step<360;k++){const v=k*step,d=Math.abs(((angle-v+540)%360)-180);if(d<distance){distance=d;best=v;}}const t=best*Math.PI/180;return [a[0]+r*Math.cos(t),a[1]+r*Math.sin(t),...b.slice(2)];}
function save(s){s.plugin.saveData(s.plugin.settings);for(const x of s.plugin.sessions.values())for(const box of x.host.querySelectorAll('.cdt-brush-snap'))sync(x,box);}
function toggle(s){const q=s.plugin.settings;ensure(q);q.brushSnapEnabled=!q.brushSnapEnabled;save(s);}
function sync(s,box){const q=s.plugin.settings;box.querySelector('input[type=checkbox]').checked=q.brushSnapEnabled;box.querySelector('select').value=q.brushSnapCustom?'custom':String(q.brushSnapAngle);const n=box.querySelector('input[type=number]');n.hidden=!q.brushSnapCustom;n.value=q.brushSnapAngle;}
function panel(s,parent,bind){const q=s.plugin.settings;ensure(q);const el=(tag,cls,parent,text)=>s.element(tag,cls,parent,text),box=el('div','cdt-brush-snap',parent),label=el('label','cdt-select-row',box),check=el('input','',label);check.type='checkbox';check.setAttribute('aria-label','브러시 각도 스냅');el('span','',label,'각도 스냅 · 모든 브러시');check.onchange=()=>toggle(s);bind(s,label,'action:brush-snap','브러시 각도 스냅',()=>toggle(s));const row=el('div','cdt-row-actions',box),select=el('select','',row);select.setAttribute('aria-label','스냅 각도 간격');for(const value of [...presets,'custom']){const o=el('option','',select,value==='custom'?'직접 지정':value+'°');o.value=String(value);}const input=el('input','',row);input.type='number';input.min='.1';input.max='180';input.step='any';input.style.width='90px';input.setAttribute('aria-label','직접 지정 각도');input.title='0.1°~180°';select.onchange=()=>{q.brushSnapCustom=select.value==='custom';if(!q.brushSnapCustom)q.brushSnapAngle=Number(select.value);save(s);};input.onchange=()=>{const v=Number(input.value);if(input.value&&Number.isFinite(v)&&v>=.1&&v<=180)q.brushSnapAngle=v;save(s);};sync(s,box);}
module.exports={ensure,point,toggle,panel};
