'use strict';
const {Notice,Modal}=require('obsidian');
const {floating}=require('./panel-layout');
const {hsvToHex,hexToHsv,clamp}=require('./color');
class ColorUI{
 constructor(s){this.s=s;this.hsv=hexToHsv(s.plugin.settings.color);this.pinned=true;this.pick=null;this.build();this.layout=floating(s,this.box,'color');}
 build(){const s=this.s,b=s.colorPopup;this.box=b;b.replaceChildren();b.setAttribute('role','dialog');b.setAttribute('aria-label','색상');const head=s.element('div','cdt-color-head',b);s.element('strong','',head,'색상');const slots=s.element('div','cdt-color-slots',b);for(const [key,label]of [['main','메인색'],['secondary','보조색']]){const button=s.element('button','',slots);button.setAttribute('aria-label',label);button.title=label+' · Z: 전환';button.dataset.colorSlot=key;button.onclick=()=>s.selectColorSlot(key);}const transparent=s.element('button','cdt-transparent-color',slots,'투명');transparent.setAttribute('aria-label','투명색 (C)');transparent.onclick=()=>{s.toggleTransparentColor();};s.button(head,'x','색상 창 닫기',()=>this.close(true));
 this.wheel=s.element('canvas','cdt-color-wheel',b);this.wheel.width=this.wheel.height=220;this.wheel.setAttribute('aria-label','색상환과 채도·명도');this.wheel.tabIndex=0;
 const row=s.element('div','cdt-color-values',b);this.native=s.element('input','',row);this.native.type='color';this.native.setAttribute('aria-label','현재 색');s.colorInput=this.native;this.hex=s.element('input','',row);this.hex.maxLength=7;this.hex.setAttribute('aria-label','색상 HEX');this.hex.onchange=()=>{if(/^#[0-9a-f]{6}$/i.test(this.hex.value))this.choose(this.hex.value.toLowerCase());else this.hex.value=s.toolColor();};this.native.onchange=()=>this.choose(this.native.value);s.button(row,'pipette','화면 색 가져오기',()=>this.startPick());
 this.swatches=s.element('div','cdt-color-swatches',b);s.plugin.settings.paletteColors=s.plugin.settings.paletteColors?.length?s.plugin.settings.paletteColors:['#ffffff','#25252d','#ec8888','#e4b078','#e7d894','#9bbb99','#88b8c2','#a7a1d9','#b8a3de','#d298ba','#82635d','#586878','#59674d','#bd7a55','#638e85','#83818a'];this.renderSwatches();
 for(const[key,label,min,max]of [[0,'색조',0,359],[1,'채도',0,100],[2,'명도',0,100]]){const row=s.element('label','cdt-color-channel',b,label),i=s.element('input','',row);i.type='range';i.min=min;i.max=max;i.dataset.channel=key;i.setAttribute('aria-label',label);i.oninput=()=>{this.hsv[key]=Number(i.value)/(key?100:1);this.draw();};i.onchange=()=>this.choose(hsvToHex(...this.hsv));}
 const pos=e=>{const r=this.wheel.getBoundingClientRect();return[(e.clientX-r.left)*220/r.width,(e.clientY-r.top)*220/r.height];};const update=e=>{const[x,y]=pos(e);if(this.drag==='hue')this.hsv[0]=(Math.atan2(y-110,x-110)*180/Math.PI+360)%360;else{this.hsv[1]=clamp((x-54)/112);this.hsv[2]=1-clamp((y-54)/112);}this.draw();};this.wheel.onpointerdown=e=>{if(e.button!==0)return;const[x,y]=pos(e),r=Math.hypot(x-110,y-110);if(r>=84&&r<=105)this.drag='hue';else if(x>=54&&x<=166&&y>=54&&y<=166)this.drag='sv';else return;e.preventDefault();e.stopPropagation();this.wheel.setPointerCapture(e.pointerId);update(e);};this.wheel.onpointermove=e=>{if(this.drag)update(e);};this.wheel.onpointerup=e=>{if(!this.drag)return;update(e);this.drag=null;this.wheel.releasePointerCapture(e.pointerId);this.choose(hsvToHex(...this.hsv));};this.wheel.onpointercancel=()=>{this.drag=null;this.sync();};s.element('p','cdt-hint',b,'Z: 메인 / 보조 전환 · X: 혼합 · C: 투명색\n2: 패널 열기 / 닫기 · 제목 드래그: 이동');this.sync();}
 renderSwatches(){const s=this.s;this.swatches.replaceChildren();s.plugin.settings.paletteColors.forEach((color,index)=>{const b=s.element('button','',this.swatches);b.style.background=color;b.title=color+' · 더블클릭: 색상 편집';b.setAttribute('aria-label','팔레트 '+(index+1)+' '+color);b.onclick=()=>this.choose(s.plugin.settings.paletteColors[index]);b.ondblclick=e=>{e.preventDefault();this.editSwatch(index);};});}
 editSwatch(index){const s=this.s,m=new Modal(s.plugin.app);m.setTitle('팔레트 색상 편집');const picker=s.element('input','',m.contentEl);picker.type='color';picker.value=s.plugin.settings.paletteColors[index];picker.setAttribute('aria-label','팔레트 색상');const hex=s.element('input','',m.contentEl);hex.value=picker.value;hex.setAttribute('aria-label','팔레트 HEX');picker.oninput=()=>hex.value=picker.value;hex.oninput=()=>{if(/^#[0-9a-f]{6}$/i.test(hex.value))picker.value=hex.value;};s.element('button','mod-cta',m.contentEl,'저장').onclick=()=>{if(!/^#[0-9a-f]{6}$/i.test(hex.value)){new Notice('# 뒤에 여섯 자리 색상 값을 입력하세요.');return;}s.plugin.settings.paletteColors[index]=hex.value.toLowerCase();s.plugin.saveData(s.plugin.settings);for(const session of s.plugin.sessions.values())session.colorUI?.renderSwatches();m.close();};s.element('button','',m.contentEl,'취소').onclick=()=>m.close();m.open();}
 draw(){const c=this.wheel.getContext('2d');c.clearRect(0,0,220,220);for(let h=0;h<360;h++){c.beginPath();c.strokeStyle=hsvToHex(h,1,1);c.lineWidth=18;c.arc(110,110,96,h*Math.PI/180,(h+1.5)*Math.PI/180);c.stroke();}c.fillStyle=hsvToHex(this.hsv[0],1,1);c.fillRect(54,54,112,112);let g=c.createLinearGradient(54,0,166,0);g.addColorStop(0,'white');g.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=g;c.fillRect(54,54,112,112);g=c.createLinearGradient(0,54,0,166);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,'black');c.fillStyle=g;c.fillRect(54,54,112,112);for(const[x,y]of [[110+96*Math.cos(this.hsv[0]*Math.PI/180),110+96*Math.sin(this.hsv[0]*Math.PI/180)],[54+112*this.hsv[1],54+112*(1-this.hsv[2])]]){c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.lineWidth=3;c.strokeStyle='#222';c.stroke();c.lineWidth=1;c.strokeStyle='white';c.stroke();}this.native.value=this.hex.value=hsvToHex(...this.hsv);for(const i of this.box.querySelectorAll('[data-channel]'))i.value=Math.round(this.hsv[+i.dataset.channel]*(+i.dataset.channel?100:1));}
 sync(){const q=this.s.plugin.settings;for(const b of this.box.querySelectorAll('[data-color-slot]')){b.style.background=(b.dataset.colorSlot==='main'?q.mainColor:q.secondaryColor);b.classList.toggle('is-active',!q.transparentColor&&q.activeColor===b.dataset.colorSlot);b.setAttribute('aria-pressed',String(!q.transparentColor&&q.activeColor===b.dataset.colorSlot));}const transparent=this.box.querySelector('.cdt-transparent-color');transparent?.classList.toggle('is-active',!!q.transparentColor);transparent?.setAttribute('aria-pressed',String(!!q.transparentColor));const color=this.s.toolColor();if(/^#[0-9a-f]{6}$/i.test(color)){this.hsv=hexToHsv(color);this.draw();}}
 toggle(){if(this.box.hidden)this.open();else this.close(true);}
 open(){if(!this.s.drawing)return;this.sync();this.box.hidden=false;this.s.plugin.settings.colorCollapsed=false;if(this.s.plugin.settings.panelPositions?.color)this.layout.apply();else {this.box.style.left='340px';this.box.style.top='24px';}this.s.plugin.saveData(this.s.plugin.settings);}
 close(save=false){this.cancelPick();this.box.hidden=true;if(save){this.s.plugin.settings.colorCollapsed=true;this.s.plugin.saveData(this.s.plugin.settings);}}
 choose(color){this.s.setToolColor(color);this.sync();if(!this.pinned)this.box.hidden=true;}
 startPick(){if(this.pick){this.cancelPick();return;}this.s.finishStroke();this.pick={tool:this.s.tool,popup:!this.box.hidden,token:Symbol()};this.box.hidden=true;this.s.cursor.hidden=true;this.s.host.classList.add('cdt-picking-color');this.s.eyedropperButton?.classList.add('is-active');new Notice('Canvas에서 색을 클릭하세요 · Esc: 취소');}
 cancelPick(){this.pendingPick=null;this.pick=null;this.s.host.classList.remove('cdt-picking-color');this.s.eyedropperButton?.classList.remove('is-active');if(this.s.lastPointer&&!this.s.disposed)this.s.updateCursor(this.s.lastPointer);}
 move(e){if(!this.pick?.held)return;e.preventDefault();e.stopImmediatePropagation();this.down({button:2,target:e.target,clientX:e.clientX,clientY:e.clientY,preventDefault(){},stopImmediatePropagation(){}});}
 up(e){if(!this.pick?.held||e.pointerId!==this.pick.pointerId)return false;e.preventDefault();e.stopImmediatePropagation();if(e.type==='pointercancel'){this.cancelPick();return true;}this.pick.held=false;this.pick.released=true;this.down({button:2,target:this.s.host,clientX:e.clientX,clientY:e.clientY,preventDefault(){},stopImmediatePropagation(){}});return true;}
 async down(e){if(!this.pick||![0,2].includes(e.button))return;const s=this.s;if(e.target.closest('.cdt-history,.cdt-panel-edge,.cdt-toolbar,.cdt-panel,.cdt-layers,.cdt-color-popup,.canvas-controls'))return;e.preventDefault();e.stopImmediatePropagation();if(this.busy){this.pendingPick=e;return;}const request=this.pick;this.busy=true;try{s.cursor.hidden=true;await new Promise(resolve=>s.win.requestAnimationFrame(()=>s.win.requestAnimationFrame(resolve)));const image=await require('@electron/remote').getCurrentWebContents().capturePage({x:Math.floor(e.clientX),y:Math.floor(e.clientY),width:1,height:1},{stayHidden:true});const img=s.doc.createElement('img');img.src=image.toDataURL();await img.decode();if(this.pick!==request||s.disposed||!s.isActive()||s.tool!==request.tool)return;const c=s.doc.createElement('canvas');c.width=c.height=1;c.getContext('2d').drawImage(img,0,0,1,1);const rgb=c.getContext('2d').getImageData(0,0,1,1).data,color='#'+[...rgb].slice(0,3).map(v=>v.toString(16).padStart(2,'0')).join('');if(!this.pendingPick){if(!request.held)this.cancelPick();if(color!==s.toolColor())this.choose(color);if(!request.held&&this.pinned&&request.popup)this.open();}}catch(error){this.cancelPick();new Notice('화면 색을 읽지 못했습니다: '+error.message);}finally{this.busy=false;const next=this.pendingPick;this.pendingPick=null;if(next&&this.pick)this.down(next);}}
 destroy(){this.cancelPick();}
}
module.exports={ColorUI};
