'use strict';
const {Notice,Modal,Menu}=require('obsidian');
const {writable,snapshot,makeLayer}=require('./layers');
const {randomUUID}=require('./storage');
const ToolList=require('./tool-list');const Shapes=require('./shape-tools');
const R=require('./raster-edit');
const clone=x=>JSON.parse(JSON.stringify(x));
const kinds=[['line','선'],['rectangle','사각형'],['ellipse','타원'],['arrow-angle','꺾인 화살표'],['arrow-curve','곡선 화살표']];
function snap45(p,a){if(!a)return p;const dx=p[0]-a[0],dy=p[1]-a[1],r=Math.hypot(dx,dy),angle=Math.round(Math.atan2(dy,dx)/(Math.PI/4))*Math.PI/4;return [a[0]+Math.cos(angle)*r,a[1]+Math.sin(angle)*r];}
function arrowPoints(points,curved){if(points.length<2)return points;let path=points;if(curved){path=[];for(let i=0;i<points.length-1;i++){const a=points[Math.max(0,i-1)],b=points[i],c=points[i+1],d=points[Math.min(points.length-1,i+2)];for(let j=0;j<24;j++){const t=j/24;path.push([0,1].map(k=>.5*((2*b[k])+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t*t+(-a[k]+3*b[k]-3*c[k]+d[k])*t*t*t)));}}path.push(points.at(-1));}const a=path.at(-2),b=path.at(-1),r=Math.atan2(b[1]-a[1],b[0]-a[0]),len=Math.min(24,Math.hypot(b[0]-points[0][0],b[1]-points[0][1])*.3);return [...path,[b[0]-len*Math.cos(r-.5),b[1]-len*Math.sin(r-.5)],b,[b[0]-len*Math.cos(r+.5),b[1]-len*Math.sin(r+.5)]];}
function shapePoints(kind,a,b){if(kind==='arrow-angle'||kind==='arrow-curve')return arrowPoints([a,[(a[0]+b[0])/2,a[1]-8],b],kind==='arrow-curve');if(kind==='rectangle')return [a,[b[0],a[1]],b,[a[0],b[1]],a];if(kind==='circle'||kind==='ellipse'){const rx=Math.abs(b[0]-a[0])/2,ry=kind==='circle'?rx:Math.abs(b[1]-a[1])/2,cx=(a[0]+b[0])/2,cy=kind==='circle'?a[1]+Math.sign(b[1]-a[1]||1)*rx:(a[1]+b[1])/2;return Array.from({length:129},(_,i)=>[cx+rx*Math.cos(i*Math.PI/64),cy+ry*Math.sin(i*Math.PI/64)]);}if(kind==='arrow'){const r=Math.atan2(b[1]-a[1],b[0]-a[0]),len=Math.min(24,Math.hypot(b[0]-a[0],b[1]-a[1])*.3);return [a,b,[b[0]-len*Math.cos(r-.5),b[1]-len*Math.sin(r-.5)],b,[b[0]-len*Math.cos(r+.5),b[1]-len*Math.sin(r+.5)]];}return [a,b];}
function promptName(s,title,initial,fn){const m=new Modal(s.plugin.app);m.setTitle(title);const i=m.contentEl.createEl('input',{type:'text',value:initial});i.setAttribute('aria-label','프리셋 이름');m.contentEl.createEl('button',{text:'저장'}).onclick=()=>{if(i.value.trim()){fn(i.value.trim());m.close();}};m.open();i.focus();}
function presets(s,panel,tool,current,apply){const settings=s.plugin.settings;settings.stylePresets??=[];const list=s.element('div','cdt-style-presets',panel);for(const p of settings.stylePresets.filter(p=>p.tool===tool)){const row=s.element('div','cdt-row-actions',list);const b=s.element('button','',row,p.name);b.onclick=()=>apply(clone(p.style));s.button(row,'more-horizontal',p.name+' 메뉴',e=>{const m=new Menu();m.addItem(i=>i.setTitle('현재 설정 저장').onClick(()=>{p.style=clone(current());s.plugin.saveData(settings);}));m.addItem(i=>i.setTitle('이름 바꾸기').onClick(()=>promptName(s,'프리셋 이름',p.name,name=>{p.name=name;s.plugin.saveData(settings);s.figures.panelRender();})));m.addItem(i=>i.setTitle('복제').onClick(()=>{settings.stylePresets.push({...clone(p),id:randomUUID(),name:p.name+' 복사'});s.plugin.saveData(settings);s.figures.panelRender();}));m.addItem(i=>i.setTitle('삭제').onClick(()=>{settings.stylePresets=settings.stylePresets.filter(x=>x!==p);s.plugin.saveData(settings);s.figures.panelRender();}));m.showAtMouseEvent(e);});}s.element('button','',panel,'＋ 현재 스타일 저장').onclick=()=>promptName(s,'스타일 프리셋','새 스타일',name=>{settings.stylePresets.push({id:randomUUID(),tool,name,style:clone(current())});s.plugin.saveData(settings);s.figures.panelRender();});}
class Figures{
 constructor(s){this.s=s;s.plugin.settings.shapeStyle??={kind:'rectangle',width:4,color:'#b6a0e2'};this.panel=s.element('aside','cdt-panel cdt-figure-panel',s.host);this.panel.hidden=true;this.svg=s.doc.createElementNS('http://www.w3.org/2000/svg','svg');this.svg.classList.add('cdt-selection');s.host.append(this.svg);this.bar=s.element('div','cdt-selection-bar',s.host);this.bar.hidden=true;s.listen(s.host,'wheel',e=>{if(this.pending&&s.tool==='shape'&&!e.target.closest('.cdt-history,.cdt-panel-edge,.cdt-panel,.cdt-layers,.cdt-toolbar')){e.preventDefault();e.stopImmediatePropagation();this.pending.width=Math.max(1,Math.min(100,this.pending.width+(e.deltaY<0?1:-1)));s.plugin.settings.shapeStyle.width=this.pending.width;this.save();this.panelRender();this.preview();}},{capture:true,passive:false});}
 save(){Shapes.remember(this.s.plugin.settings);this.s.plugin.saveData(this.s.plugin.settings);}
 panelRender(){const s=this.s;this.panel.hidden=!(s.drawing&&s.tool==='shape'||!s.drawing&&s.tool==='text'&&!s.textItems?.panelClosed);if(this.panel.hidden)return;this.panel.replaceChildren();if(s.tool==='text'){s.textItems?.panelRender(this.panel);return;}const st=s.plugin.settings.shapeStyle;s.element('div','cdt-panel-heading',this.panel,'도형');const order=s.plugin.settings.shapeOrder||kinds.map(k=>k[0]);for(const t of Shapes.ensure(s.plugin.settings).slice().sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id))){const k=t.id,name=t.name,kind=t.style.kind;const b=s.element('button','cdt-shape-kind'+(s.plugin.settings.selectedShape===k?' is-active':''),this.panel);b.setAttribute('aria-label',name);ToolList.badge(s,b,'shape:'+k);ToolList.draggable(s,b,k,()=>[...(s.plugin.settings.shapeOrder||kinds.map(k=>k[0]))],ids=>{s.plugin.settings.shapeOrder=ids;this.save();},()=>this.panelRender());const svg=s.doc.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 200 40');const path=s.doc.createElementNS(svg.namespaceURI,'polyline');path.setAttribute('points',shapePoints(kind,kind==='circle'?[80,5]:[15,10],kind==='circle'?[110,35]:[185,kind==='line'||kind==='arrow'?10:30]).map(p=>p.join(',')).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','currentColor');path.setAttribute('stroke-width','2');svg.append(path);b.append(svg,s.doc.createTextNode(name));b.oncontextmenu=e=>{e.preventDefault();s.quickTools.context('shape:'+k,e);};b.onclick=()=>Shapes.choose(s,k);}this.properties(this.panel);s.quickTools?.render();}
 properties(panel){const s=this.s,st=require('./shape-material').ensure(s.plugin.settings.shapeStyle);this.field(panel,'선 굵기',st.width,1,100,v=>{st.width=v;if(this.pending){this.pending.width=v;this.preview();}this.save();});this.field(panel,'불투명도',Math.round(st.opacity*100),0,100,v=>{st.opacity=v/100;if(this.pending){this.pending.opacity=st.opacity;this.preview();}this.save();});for(const[k,name]of [['tip','브러시 끝 설정'],['texture','질감 설정']])s.element('button','',panel,name).onclick=()=>require('./shape-material').open(this,k);const c=s.element('input','',panel);c.type='color';c.value=st.color;c.setAttribute('aria-label','도형 색');c.oninput=()=>{st.color=c.value;if(this.pending){this.pending.color=c.value;this.preview();}this.save();};s.element('p','cdt-hint',panel,'일반 도형: 드래그 생성 · 손잡이 조절 · Shift+타원: 원\n선 / 화살표: 클릭으로 점 추가 · 점 드래그로 조절 · Shift+선/화살표: 45° 맞춤\n더블클릭: 확정 · Enter: 확정 · Ctrl+Z: 마지막 점 취소 · Esc: 전체 취소');presets(s,panel,'shape',()=>st,value=>{this.confirm();s.plugin.settings.shapeStyle={...value,kind:value.kind==='circle'?'ellipse':value.kind};this.save();this.panelRender();});}
 field(parent,label,value,min,max,change){const s=this.s,row=s.element('label','cdt-property-body',parent);s.element('span','',row,label);const line=s.element('div','cdt-range-line',row),range=s.element('input','',line),number=s.element('input','',line);range.type='range';number.type='number';for(const i of [range,number]){i.min=min;i.max=max;i.value=value;i.setAttribute('aria-label',label+(i===range?' 슬라이더':''));i.oninput=()=>{const v=Math.max(min,Math.min(max,Number(i.value)||min));range.value=number.value=v;change(v);};}}
 target(){const s=this.s,d=s.record.data,l=d.layers.find(l=>l.id===d.selectedLayers[0]);if(l?.alphaLock&&s.plugin.settings.transparentColor){new Notice('투명 부분 잠금 중에는 지울 수 없습니다.');return null;}if(l?.type==='layer'&&writable(d,l))return l;if(!d.layers.length){const l=makeLayer('Layer 1');return l;}new Notice('도형을 그릴 숨김·잠금 없는 레이어를 선택해주세요.');return null;}
 down(e){const s=this.s;if(s.tool!=='shape')return false;if(e.button!==0)return true;e.preventDefault();e.stopImmediatePropagation();s.doc.activeElement?.blur();let p=s.point(e);const h=e.target.dataset?.shapeHandle;const kind=s.plugin.settings.shapeStyle.kind;if(['line','arrow-angle','arrow-curve'].includes(kind)&&e.shiftKey&&e.target.dataset?.controlPoint===undefined)p=snap45(p,this.pending?.controlPoints?.at(-1));if(kind==='line'||kind==='arrow-angle'||kind==='arrow-curve'){if(!this.pending){const layer=this.target();if(!layer)return true;this.pending={...clone(s.plugin.settings.shapeStyle),transparentColor:s.plugin.settings.transparentColor,id:randomUUID(),layer,points:[p],controlPoints:[],matrix:R.identity(),revision:s.record.data.revision};}this.hoverPoint=null;this.tapStart={id:e.pointerId,x:e.clientX,y:e.clientY};const cp=e.target.dataset?.controlPoint;if(cp!==undefined){this.drag={id:e.pointerId,handle:'point',index:Number(cp)};s.host.setPointerCapture(e.pointerId);}else {const last=this.pending.controlPoints.at(-1);const repeat=this.lastTap&&e.timeStamp-this.lastTap.time<=250&&Math.hypot(e.clientX-this.lastTap.x,e.clientY-this.lastTap.y)<=6;if(!repeat&&(!last||Math.hypot(p[0]-last[0],p[1]-last[1])>.5/(s.canvas.scale||1)))this.pending.controlPoints.push(p);}this.pending.points=kind==='line'?this.pending.controlPoints.map(p=>p.slice()):arrowPoints(this.pending.controlPoints,kind==='arrow-curve');this.preview();return true;}if(this.pending&&(h||this.hit(p))){this.drag={id:e.pointerId,start:p,matrix:this.pending.matrix.slice(),handle:h||'move'};}else{this.confirm();const l=this.target();if(!l)return true;this.startLayer=l;this.drag={id:e.pointerId,start:p,handle:'new'};}s.host.setPointerCapture(e.pointerId);return true;}
 hit(p){const q=R.point(R.inverse(this.pending.matrix),p),b=R.bounds(this.pending.points);return q[0]>=b.left-8&&q[0]<=b.right+8&&q[1]>=b.top-8&&q[1]<=b.bottom+8;}
 move(e){if(this.tapStart?.id===e.pointerId&&Math.hypot(e.clientX-this.tapStart.x,e.clientY-this.tapStart.y)>6){this.tapStart.moved=true;this.lastTap=null;}if(!this.drag){if(this.pending?.controlPoints&&this.s.drawing&&this.s.tool==='shape'&&!this.s.space&&!this.s.canvas.isHoldingSpace&&this.s.host.contains(e.target)&&!e.target.closest('.cdt-history,.cdt-panel-edge,.cdt-panel,.cdt-layers,.cdt-toolbar,.cdt-color-popup,.canvas-controls')){e.preventDefault();e.stopImmediatePropagation();const p=this.s.point(e);this.hoverPoint=e.shiftKey?snap45(p,this.pending.controlPoints.at(-1)):p;this.updatePath(true);this.preview();return true;}if(this.hoverPoint){this.hoverPoint=null;this.updatePath(false);this.preview();}return false;}if(e.pointerId!==this.drag.id)return false;e.preventDefault();e.stopImmediatePropagation();const s=this.s,d=this.drag,p=s.point(e);if(d.handle==='point'){this.pending.controlPoints[d.index]=e.shiftKey?snap45(p,this.pending.controlPoints[d.index===0?1:d.index-1]):p;this.pending.points=this.pending.kind==='line'?this.pending.controlPoints.map(p=>p.slice()):arrowPoints(this.pending.controlPoints,this.pending.kind==='arrow-curve');this.preview();return true;}if(d.handle==='new'){if(Math.hypot(p[0]-d.start[0],p[1]-d.start[1])<3&&!this.pending)return true;const st=s.plugin.settings.shapeStyle;this.pending={...clone(st),transparentColor:s.plugin.settings.transparentColor,id:randomUUID(),layer:this.startLayer,points:shapePoints(st.kind==='ellipse'&&e.shiftKey?'circle':st.kind,d.start,p),matrix:R.identity(),revision:s.record.data.revision};}else{const b=R.bounds(this.pending.points),center=[(b.left+b.right)/2,(b.top+b.bottom)/2];if(d.handle==='move')this.pending.matrix=R.multiply(R.translation(p[0]-d.start[0],p[1]-d.start[1]),d.matrix);else if(d.handle==='rotate'){const c=R.point(d.matrix,center);let a=Math.atan2(p[1]-c[1],p[0]-c[0])-Math.atan2(d.start[1]-c[1],d.start[0]-c[0]);if(e.shiftKey)a=Math.round(a/(Math.PI/12))*Math.PI/12;this.pending.matrix=R.multiply(R.around(c,[Math.cos(a),Math.sin(a),-Math.sin(a),Math.cos(a),0,0]),d.matrix);}else{const a=[d.handle.includes('w')?b.right:b.left,d.handle.includes('n')?b.bottom:b.top],q=R.point(R.inverse(d.matrix),p),start=R.point(R.inverse(d.matrix),d.start);let x=(q[0]-a[0])/(start[0]-a[0]||1),y=(q[1]-a[1])/(start[1]-a[1]||1);if(e.shiftKey||this.pending.kind==='circle')x=y=Math.abs(x)>Math.abs(y)?x:y;this.pending.matrix=R.multiply(d.matrix,R.around(a,[x,0,0,y,0,0]));}}this.preview();return true;}
 up(e){const tap=this.tapStart?.id===e.pointerId?this.tapStart:null;if(tap){this.tapStart=null;if(e.type!=='pointercancel'&&!tap.moved&&this.pending?.controlPoints){const last=this.lastTap;this.lastTap={x:e.clientX,y:e.clientY,time:e.timeStamp};if(last&&e.timeStamp-last.time<=250&&Math.hypot(e.clientX-last.x,e.clientY-last.y)<=6){e.preventDefault();e.stopImmediatePropagation();this.confirm();return true;}}else this.lastTap=null;}if(this.drag?.id!==e.pointerId)return !!tap;e.preventDefault();e.stopImmediatePropagation();if(this.s.host.hasPointerCapture(e.pointerId))this.s.host.releasePointerCapture(e.pointerId);this.drag=null;if(e.type==='pointercancel')this.cancel();return true;}
 stroke(){const p=this.pending,l=p.layer,o=l.offset||{x:0,y:0};return {id:p.id,layerId:l.id,tool:p.transparentColor?'eraser':'brush',color:p.color,size:p.width,...Object.fromEntries(Object.entries(require('./shape-material').defaults).map(([k,v])=>[k,p[k]??v])),stabilization:0,blend:'source-over',paintAmount:1,colorStretch:0,mix:false,scatter:false,particleCount:1,particleSize:1,spread:0,alphaLock:l.alphaLock,points:p.points.map(q=>{const v=R.point(p.matrix,q);return [v[0]-o.x,v[1]-o.y,1,1,1,0];})};}
 preview(){if(!this.pending)return;const s=this.s,d=s.record.data,p=this.pending;if(d.revision!==p.revision||(d.layers.includes(p.layer)&&!writable(d,p.layer))){this.cancel();new Notice('레이어가 변경되어 임시 도형을 취소했습니다.');return;}this.previewData={...d,layers:d.layers.includes(p.layer)?d.layers:[p.layer,...d.layers],strokes:[...d.strokes,this.stroke()]};s.scheduleRender();}
 updatePath(hover=false){const p=this.pending;if(!p?.controlPoints)return;const points=p.controlPoints.map(q=>q.slice());if(hover&&this.hoverPoint&&(!points.length||Math.hypot(this.hoverPoint[0]-points.at(-1)[0],this.hoverPoint[1]-points.at(-1)[1])>.5/(this.s.canvas.scale||1)))points.push(this.hoverPoint.slice());p.points=p.kind==='line'?points:arrowPoints(points,p.kind==='arrow-curve');}
 confirm(includeHover=false){if(!this.pending)return;if(includeHover&&this.hoverPoint&&this.pending.controlPoints){const last=this.pending.controlPoints.at(-1);if(!last||Math.hypot(this.hoverPoint[0]-last[0],this.hoverPoint[1]-last[1])>.5/(this.s.canvas.scale||1))this.pending.controlPoints.push(this.hoverPoint.slice());}this.hoverPoint=null;this.updatePath(false);if(this.pending.controlPoints&&this.pending.controlPoints.length<2){this.cancel();return;}this.preview();if(!this.pending)return;const s=this.s,d=s.record.data,p=this.pending,before=snapshot(d);if(!d.layers.includes(p.layer)){d.layers.push(p.layer);d.selectedLayers=[p.layer.id];}d.strokes.push(require('./history-state').freeze(require('./materials').freezeMaterials(this.stroke(),d)));s.record.history.push(before);s.plugin.store.changed(s.record);s.plugin.queueSave();this.cancel();s.plugin.refreshLayers(s.record);s.plugin.repaint(s.record);}
 cancel(){this.hoverPoint=null;this.tapStart=null;this.lastTap=null;if(this.drag&&this.s.host.hasPointerCapture(this.drag.id))this.s.host.releasePointerCapture(this.drag.id);this.drag=null;this.pending=null;this.previewData=null;this.s.scheduleRender();}
 undoPoint(){if(!this.pending?.controlPoints){this.cancel();return;}const removed=this.pending.controlPoints.pop();if(!this.pending.controlPoints.length){this.cancel();return;}this.tapStart=null;this.lastTap=null;if(this.drag&&this.s.host.hasPointerCapture(this.drag.id))this.s.host.releasePointerCapture(this.drag.id);this.drag=null;this.hoverPoint??=removed;this.updatePath(true);this.preview();}
 key(e){if(!this.pending)return false;if(['Enter','Escape'].includes(e.code)||((e.ctrlKey||e.metaKey)&&e.code==='KeyZ')){e.preventDefault();e.stopImmediatePropagation();if(e.code==='Enter')this.confirm(true);else if(e.code==='KeyZ'){if(!e.shiftKey)this.undoPoint();}else this.cancel();return true;}return false;}
 render(){this.svg.replaceChildren();this.bar.hidden=true;if(!this.pending)return;const s=this.s,p=this.pending,cr=s.canvas.canvasEl.getBoundingClientRect(),hr=s.host.getBoundingClientRect(),scale=cr.width/s.canvas.canvasEl.offsetWidth,screen=q=>{const v=R.point(p.matrix,q);return [v[0]*scale+cr.left-hr.left,v[1]*scale+cr.top-hr.top];},b=R.bounds(p.points);const add=(tag,a)=>{const n=s.doc.createElementNS(this.svg.namespaceURI,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,v);this.svg.append(n);};if(p.controlPoints){p.controlPoints.forEach((q,i)=>{const[x,y]=screen(q);add('circle',{cx:x,cy:y,r:5,'data-control-point':i,class:'cdt-transform-handle'});});if(this.hoverPoint){const[x,y]=screen(this.hoverPoint);add('circle',{cx:x,cy:y,r:5,fill:'none',stroke:'var(--interactive-accent)','stroke-dasharray':'2 2','pointer-events':'none'});}this.bar.style.left='340px';this.bar.style.top='20px';return;}const poly=R.corners(b).map(screen);add('polygon',{points:poly.map(q=>q.join(',')).join(' '),class:'cdt-transform-box'});for(const[k,q]of Object.entries({nw:[b.left,b.top],ne:[b.right,b.top],se:[b.right,b.bottom],sw:[b.left,b.bottom]})){const[x,y]=screen(q);add('rect',{x:x-4,y:y-4,width:8,height:8,'data-shape-handle':k,class:'cdt-transform-handle'});}const top=screen([(b.left+b.right)/2,b.top]);add('circle',{cx:top[0],cy:top[1]-28,r:5,'data-shape-handle':'rotate',class:'cdt-transform-handle'});const sb=R.bounds(poly);this.bar.style.left=Math.max(60,Math.min(hr.width-420,sb.left))+'px';this.bar.style.top=Math.max(8,Math.min(hr.height-70,sb.bottom+16))+'px';}
 destroy(){this.confirm();this.panel.remove();this.svg.remove();this.bar.remove();}
}
module.exports={Figures,shapePoints,arrowPoints,presets,snap45};


