'use strict';
const {Modal,PluginSettingTab,Setting,Notice}=require('obsidian');
function confirm(app,title,message){return new Promise(resolve=>{let accepted=false;const modal=new Modal(app);modal.onOpen=()=>{modal.titleEl.textContent=title;modal.contentEl.createEl('p',{text:message,cls:'cdt-history-message'});const row=modal.contentEl.createDiv({cls:'cdt-history-actions'});const cancel=row.createEl('button',{text:'취소'});cancel.onclick=()=>modal.close();const yes=row.createEl('button',{text:title==='히스토리를 비울까요?'?'비우기':'적용',cls:'mod-warning'});yes.onclick=()=>{accepted=true;modal.close()};cancel.focus();};modal.onClose=()=>resolve(accepted);modal.open();});}
const busy=s=>!!(s.active||s.figures?.pending||s.selection?.dirty||s.selection?.pasting||s.selection?.drag||s.layerUI?.opacityBefore);
const recordBusy=s=>[...s.plugin.sessions.values()].some(t=>t.record===s.record&&busy(t));
class HistoryUI{
 constructor(s){this.s=s;const host=s.element('div','cdt-history',s.host);this.host=host;this.details=s.element('button','cdt-history-summary',host);this.details.setAttribute('aria-label','히스토리 상세');this.details.onclick=()=>this.showDetails();this.meter=s.element('progress','',host);this.meter.setAttribute('aria-label','히스토리 보관 횟수');this.memory=s.element('span','',host);this.clear=s.element('button','',host,'비우기');this.clear.setAttribute('aria-label','현재 Canvas 히스토리 비우기');this.clear.onclick=()=>this.empty();for(const type of ['pointerdown','pointerup','mousedown','mouseup','click','dblclick','contextmenu'])s.listen(host,type,e=>e.stopPropagation());this.update();}
 update(){const h=this.s.record?.history;if(!h)return;this.details.textContent=`히스토리 ${h.count} / ${h.limit}회`;this.details.title=`실행 취소 ${h.r.undo.length}회 · 다시 실행 ${h.r.redo.length}회`;this.meter.max=h.limit;this.meter.value=h.count;this.memory.textContent=`약 ${(h.bytes/1048576).toFixed(1)}MB`;this.memory.title='Undo·Redo 보관 자료 추정량입니다. 화면 캐시와 Obsidian 전체 메모리는 포함하지 않습니다.';this.updateBusy();}
 updateBusy(){this.clear.disabled=!this.s.record?.history?.count||recordBusy(this.s);this.host.classList.toggle('has-save-error',!!this.s.record?.error);}
 showDetails(){const h=this.s.record.history,m=new Modal(this.s.plugin.app);m.onOpen=()=>{m.titleEl.textContent='현재 Canvas 히스토리';m.contentEl.createEl('p',{text:`실행 취소 ${h.r.undo.length}회 · 다시 실행 ${h.r.redo.length}회\n보관 ${h.count} / ${h.limit}회 · 약 ${(h.bytes/1048576).toFixed(1)}MB`,cls:'cdt-history-message'});m.contentEl.createEl('p',{text:'메모리는 공유 자료를 중복 계산하지 않은 추정량입니다. 최대 횟수는 플러그인 설정에서 변경할 수 있습니다.'});};m.open();}
 async empty(){const s=this.s;if(recordBusy(s))return;if(await confirm(s.plugin.app,'히스토리를 비울까요?','현재 Canvas의 실행 취소·다시 실행 기록을 삭제합니다.\n그림은 그대로 유지됩니다.\n비우기 이전 작업으로 되돌릴 수 없습니다.')){if(s.disposed||recordBusy(s))return;s.record.history.clear();}}
 destroy(){this.host.remove();}
}
class HistorySettings extends PluginSettingTab{
 constructor(app,plugin){super(app,plugin);this.plugin=plugin;}
 display(){const p=this.plugin;this.containerEl.empty();this.containerEl.createEl('h2',{text:'히스토리'});let input;new Setting(this.containerEl).setName('실행 취소 최대 횟수').setDesc('모든 Canvas에 같은 한도를 적용합니다. 기록은 Canvas별로 보관하며, 메모리 용량으로 자동 삭제하지 않습니다.').addText(t=>{input=t;t.inputEl.type='number';t.inputEl.min='1';t.inputEl.step='1';t.setValue(String(p.settings.historyLimit||50));t.inputEl.setAttribute('aria-label','실행 취소 최대 횟수');}).addButton(b=>b.setButtonText('적용').onClick(async()=>{const value=Number(input.getValue());if(!Number.isSafeInteger(value)||value<1){new Notice('1 이상의 정수를 입력해주세요.');return;}if([...p.sessions.values()].some(busy)){new Notice('작성 중인 획이나 변형을 확정한 뒤 변경해주세요.');return;}const affected=[...p.store.records.values()].filter(r=>r.history?.count>value);if(affected.length&&!await confirm(p.app,'히스토리 한도를 줄일까요?',affected.map(r=>`${r.data.sourcePath}: ${r.history.count-value}개 기록 삭제`).join('\n')+'\n오래된 기록은 복구할 수 없습니다.')){input.setValue(String(p.settings.historyLimit||50));return;}p.settings.historyLimit=value;for(const r of p.store.records.values())r.history?.trim(value);await p.saveData(p.settings);}));}
}
module.exports={HistoryUI,HistorySettings};
