'use strict';
const {ancestors}=require('./layers');
function hit(s,e){const d=s.record.data,[x,y]=s.point(e),tx=Math.floor(x/256),ty=Math.floor(y/256),px=Math.floor(x-tx*256),py=Math.floor(y-ty*256);for(const l of d.layers){if(l.type!=='layer'||![l,...ancestors(d,l)].every(a=>a.visible&&a.opacity>0))continue;if(s.layerUI.solo.length&&!s.layerUI.solo.some(id=>id===l.id||ancestors(d,l).some(a=>a.id===id)))continue;const tiles=s.engine.composite(d,null,null,s.layerUI.solo,new Set([l.id])),t=tiles.get(tx+','+ty);if(t&&t.c.getContext('2d').getImageData(px,py,1,1).data[3]>0)return l;}return null;}
function reveal(s,ids){const d=s.record.data;s.figures.confirm();s.selection.confirm(false);s.selection.end();s.finishStroke();d.selectedLayers=[...ids];for(const l of d.layers.filter(l=>ids.includes(l.id)))for(const a of ancestors(d,l))a.expanded=true;s.plugin.settings.layersCollapsed=false;s.layerUI.revealed=new Set(ids);s.layerUI.render();s.workspaceUI.applyLayout();const row=s.layers.querySelector('.cdt-layer-row.is-active'),list=s.layers.querySelector('.cdt-layer-list');if(row&&list){const r=row.getBoundingClientRect(),b=list.getBoundingClientRect();if(r.top<b.top)list.scrollTop-=b.top-r.top;else if(r.bottom>b.bottom)list.scrollTop+=r.bottom-b.bottom;}s.plugin.store.changed(s.record);s.plugin.queueSave();}
function clearHover(s){if(s.layerHoverFrame){s.win.cancelAnimationFrame(s.layerHoverFrame);s.layerHoverFrame=null;}s.layerTip?.remove();s.layerTip=null;}
function hover(s,e){const target=e?.target;if(!s.ready||!s.drawing||!s.isActive()||!['rectangle','lasso'].includes(s.tool)||!e?.altKey||e.ctrlKey||e.metaKey||e.buttons||s.selection.drag||s.selection.pasting||s.colorUI.pick||!target||!s.host.contains(target)||target.closest('.cdt-history,.cdt-panel-edge,.cdt-toolbar,.cdt-panel,.cdt-layers,.cdt-color-popup,.cdt-selection-bar,.canvas-controls,.canvas-menu')){clearHover(s);return;}s.layerHoverEvent=e;if(s.layerHoverFrame)return;s.layerHoverFrame=s.win.requestAnimationFrame(()=>{s.layerHoverFrame=null;if(s.disposed)return;const event=s.layerHoverEvent,l=hit(s,event);if(!l){clearHover(s);return;}clearTimeout(s.layerTipTimer);const h=s.host.getBoundingClientRect();s.layerTip??=s.element('div','cdt-layer-name-tip',s.host);s.layerTip.textContent=l.name;s.layerTip.style.left=Math.min(h.width-160,Math.max(0,event.clientX-h.left))+'px';s.layerTip.style.top=Math.max(0,event.clientY-h.top-36)+'px';});}
function down(s,e){if(e.button!==0||e.shiftKey||e.ctrlKey&&e.altKey||(!e.ctrlKey&&!e.altKey))return false;const l=hit(s,e);e.preventDefault();e.stopImmediatePropagation();s.layerTip?.remove();s.layerTip=null;if(!l)return true;if(e.altKey){const h=s.host.getBoundingClientRect();s.layerTip=s.element('div','cdt-layer-name-tip',s.host,l.name);s.layerTip.style.left=Math.min(h.width-160,Math.max(0,e.clientX-h.left))+'px';s.layerTip.style.top=Math.max(0,e.clientY-h.top-36)+'px';clearTimeout(s.layerTipTimer);s.layerTipTimer=setTimeout(()=>s.layerTip?.remove(),1600);return true;}reveal(s,[l.id]);s.doc.activeElement?.blur();s.ctrlPick={id:e.pointerId,x:e.clientX,y:e.clientY,tool:s.tool,event:{pointerId:e.pointerId,button:0,clientX:e.clientX,clientY:e.clientY,target:s.host,preventDefault(){},stopImmediatePropagation(){}}};s.host.setPointerCapture(e.pointerId);return true;}
function move(s,e){const p=s.ctrlPick;if(!p||p.id!==e.pointerId)return false;e.preventDefault();e.stopImmediatePropagation();if(Math.hypot(e.clientX-p.x,e.clientY-p.y)<5)return true;s.ctrlPick=null;s.ctrlObject=p.tool;s.selectTool('move-layer');s.selection.safe(()=>s.selection.down(p.event));s.selection.safe(()=>s.selection.move(e));return true;}
function up(s,e){if(s.ctrlPick?.id!==e.pointerId)return false;s.ctrlPick=null;if(s.host.hasPointerCapture(e.pointerId))s.host.releasePointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation();return true;}
module.exports={hit,reveal,down,move,up,hover,clearHover};
