'use strict';
const {Menu,Notice}=require('obsidian');
const {blends,makeLayer,descendants,ancestors,writable,snapshot}=require('./layers');
const clone=x=>JSON.parse(JSON.stringify(x));
const blendNames=['보통','곱하기','스크린','오버레이','어둡게','밝게','색상 닷지','색상 번','하드 라이트','소프트 라이트','차이','제외','색조','채도','색상','광도'];
class LayerUI{
 constructor(s){this.s=s;this.search='';this.filter='all';this.label='';this.solo=[];this.thumbs=new Map();}
 get d(){return this.s.record.data;}get chosen(){return this.d.layers.filter(l=>this.d.selectedLayers.includes(l.id));}
 get current(){return this.chosen[0];}
 el(tag,cls,parent,text){return this.s.element(tag,cls,parent,text);}
 icon(parent,icon,label,action){return this.s.button(parent,icon,label,action);}
 change(fn){this.s.figures?.confirm();this.s.selection?.confirm(false);this.s.selection?.end();this.s.finishStroke();const before=snapshot(this.d);try{fn();require('./history-state').seal(this.d);}catch(e){Object.assign(this.d,before);new Notice(e.message);return;}this.s.record.history.push(before);this.s.plugin.store.changed(this.s.record);this.s.plugin.queueSave();this.s.plugin.repaint(this.s.record);this.s.plugin.refreshLayers(this.s.record);}
 select(id,e={}){this.s.figures?.confirm();this.s.selection?.confirm(false);this.s.selection?.end();const visible=this.rows.map(l=>l.id),a=visible.indexOf(this.last),b=visible.indexOf(id);if(e.shiftKey&&a>=0&&b>=0)this.d.selectedLayers=visible.slice(Math.min(a,b),Math.max(a,b)+1);else if(e.ctrlKey||e.metaKey)this.d.selectedLayers=this.d.selectedLayers.includes(id)?this.d.selectedLayers.filter(v=>v!==id):[...this.d.selectedLayers,id];else this.d.selectedLayers=[id];this.last=id;this.s.plugin.store.changed(this.s.record);this.s.plugin.queueSave();for(const s of this.s.plugin.sessions.values())if(s.record===this.s.record)s.layerUI?.selectionRefresh();}
 selectionRefresh(){if(this.linkButton){const linked=this.s.anchors?.linked();require('obsidian').setIcon(this.linkButton,linked?'unlink':'link');this.linkButton.setAttribute('aria-label',linked?'연결 해제':'Canvas에서 연결 대상 고르기');this.linkButton.title=this.linkButton.getAttribute('aria-label');}const l=this.current,p=this.s.layers;for(const row of p.querySelectorAll('[data-layer-id]'))row.classList.toggle('is-active',this.d.selectedLayers.includes(row.dataset.layerId));for(const e of p.querySelectorAll('input[aria-label^="레이어 불투명도"],select[aria-label="레이어 합성 모드"],select[aria-label="레이어 색 라벨"]')){e.disabled=!l;e.value=e.getAttribute('aria-label')==='레이어 합성 모드'?(l?.blend||'source-over'):e.getAttribute('aria-label')==='레이어 색 라벨'?(l?.colorLabel||''):(l?.opacity??1)*100;}for(const [key,label]of [['locked','잠금'],['alphaLock','투명 부분 잠금'],['clip','아래 레이어에 클립']]){const b=p.querySelector(`[aria-label="${label}"]`);require('./ui-actions').bind(this.s,b,'action:layer:'+key,label,()=>{if(this.current)this.change(()=>{const v=!this.current[key];for(const n of this.chosen)if(key==='locked'||n.type==='layer')n[key]=v})});b.disabled=!l||(key!=='locked'&&l.type!=='layer');b.setAttribute('aria-pressed',String(!!l?.[key]));b.classList.toggle('is-active',!!l?.[key]);}for(const b of p.querySelectorAll('.cdt-layer-footer button'))b.disabled=!this.chosen.length&&!['레이어 추가','그룹 추가'].includes(b.getAttribute('aria-label'));}
 add(type){this.change(()=>{const current=this.current,parent=type==='layer'&&current?.type==='group'?current.id:current?.parent||null,l=makeLayer(type==='group'?'그룹':`Layer ${this.d.layers.filter(l=>l.type==='layer').length+1}`,type,parent);l.anchor=clone(this.d.layers.find(x=>x.id===parent)?.anchor||null);const i=current?this.d.layers.indexOf(current):0;this.d.layers.splice(i,0,l);this.d.selectedLayers=[l.id];});}
 topSelection(){return this.chosen.filter(l=>!ancestors(this.d,l).some(a=>this.d.selectedLayers.includes(a.id)));}
 remove(){this.change(()=>{const ids=new Set(this.topSelection().flatMap(l=>[...descendants(this.d,l.id)]));this.d.layers=this.d.layers.filter(l=>!ids.has(l.id));this.d.strokes=this.d.strokes.filter(s=>!ids.has(s.layerId));this.d.selectedLayers=this.d.layers[0]?[this.d.layers[0].id]:[];this.solo=this.solo.filter(id=>!ids.has(id));});}
 duplicate(){this.change(()=>{const roots=this.topSelection(),selected=[];for(const root of roots){const ids=descendants(this.d,root.id),map=new Map([...ids].map(id=>[id,makeLayer().id])),layers=this.d.layers.filter(l=>ids.has(l.id)).map(l=>({...clone(l),id:map.get(l.id),parent:map.get(l.parent)||l.parent,name:l.id===root.id?l.name+' 복사':l.name})),strokes=this.d.strokes.filter(s=>ids.has(s.layerId)).map(s=>({...clone(s),id:makeLayer().id,layerId:map.get(s.layerId)}));this.d.layers.splice(this.d.layers.indexOf(root),0,...layers);this.d.strokes.push(...strokes);selected.push(map.get(root.id));}this.d.selectedLayers=selected;});}
 group(){this.change(()=>{const roots=this.topSelection();if(!roots.length)return;const parent=roots[0].parent;if(roots.some(l=>l.parent!==parent))throw Error('같은 그룹 안의 항목을 선택해주세요.');const g=makeLayer('그룹','group',parent);g.anchor=clone(this.d.layers.find(l=>l.id===parent)?.anchor||null);this.d.layers.splice(this.d.layers.indexOf(roots[0]),0,g);for(const l of roots)l.parent=g.id;this.d.selectedLayers=[g.id];});}
 ungroup(){this.change(()=>{for(const g of this.chosen.filter(l=>l.type==='group')){for(const id of descendants(this.d,g.id)){const l=this.d.layers.find(n=>n.id===id);l.anchor=null;}for(const l of this.d.layers.filter(l=>l.parent===g.id))l.parent=g.parent;this.d.layers=this.d.layers.filter(l=>l.id!==g.id);}this.d.selectedLayers=[];});}
 clearDrop(){this.drop=null;for(const row of this.s.layers.querySelectorAll('.cdt-drop-before,.cdt-drop-after,.cdt-drop-inside')){row.classList.remove('cdt-drop-before','cdt-drop-after','cdt-drop-inside');row.removeAttribute('data-drop-hint');}}
 showDrop(row,l,e){if(!e.dataTransfer.types.includes('application/cdt-layers'))return;const invalid=this.dragIds?.some(id=>descendants(this.d,id).has(l.id));if(invalid){this.clearDrop();e.dataTransfer.dropEffect='none';return;}e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';const r=row.getBoundingClientRect(),t=(e.clientY-r.top)/r.height;const zone=l.type==='group'&&t>.25&&t<.75?'inside':t<.5?'before':'after';if(this.drop?.id===l.id&&this.drop.zone===zone)return;this.clearDrop();row.classList.add('cdt-drop-'+zone);row.dataset.dropHint=zone==='inside'?'그룹 안에 넣기':zone==='before'?'이 위에 넣기':'이 아래에 넣기';this.drop={id:l.id,zone};}
 finishDrop(e){e.preventDefault();e.stopPropagation();const drop=this.drop,ids=JSON.parse(e.dataTransfer.getData('application/cdt-layers')||'[]');this.clearDrop();if(drop&&ids.length)this.move(ids,drop.id,drop.zone==='inside',drop.zone==='after');}
 async move(ids,target,inside=false,after=false){const destination=this.d.layers.find(l=>l.id===target);if(!destination)return;const parentLayer=inside?destination:this.d.layers.find(l=>l.id===destination.parent),anchor=parentLayer?.anchor;if(anchor){const set=this.s.anchors.affected(ids);if(this.d.layers.some(l=>set.has(l.id)&&l.anchor&&l.anchor.targetId!==anchor.targetId)&&!await this.s.anchors.ask('그룹 연결 상속','이 그룹 안으로 옮기면 그룹의 연결 대상을 따릅니다. 그림 위치는 유지됩니다.',[['옮기기',true]]))return;}this.change(()=>{const picked=this.d.layers.filter(l=>ids.includes(l.id)&&!ancestors(this.d,l).some(a=>ids.includes(a.id)));const all=new Set(picked.flatMap(l=>[...descendants(this.d,l.id)]));if(all.has(target))throw Error('자기 자신이나 내부 항목으로 이동할 수 없습니다.');const dest=this.d.layers.find(l=>l.id===target),parent=inside?dest.id:dest.parent,bundle=this.d.layers.filter(l=>all.has(l.id));this.d.layers=this.d.layers.filter(l=>!all.has(l.id));for(const l of picked)l.parent=parent;if(anchor)for(const l of bundle)l.anchor=clone(anchor);let i=this.d.layers.indexOf(dest)+(after?1:0);if(inside)i++;this.d.layers.splice(i,0,...bundle);this.d.selectedLayers=picked.map(l=>l.id);});}
 rename(l,span){span.replaceChildren();const input=this.el('input','cdt-layer-rename',span);input.value=l.name;input.setAttribute('aria-label','레이어 이름');let done=false;const save=()=>{if(done)return;done=true;const name=input.value.trim();if(name&&name!==l.name)this.change(()=>l.name=name);else this.render();};input.onkeydown=e=>{e.stopPropagation();if(e.key==='Enter')save();if(e.key==='Escape'){done=true;this.render();}};input.onblur=save;input.focus();input.select();}
 async merge(){let roots=this.topSelection();if(!roots.length)return;if(roots.length===1&&roots[0].type==='layer'){const siblings=this.d.layers.filter(l=>l.parent===roots[0].parent),below=siblings[siblings.indexOf(roots[0])+1];if(!below){new Notice('아래에 병합할 레이어가 없습니다.');return;}roots=[roots[0],below];}if(roots.some(l=>l.parent!==roots[0].parent)){new Notice('같은 그룹 안의 항목을 선택해주세요.');return;}if(roots.some(l=>l.locked||ancestors(this.d,l).some(a=>a.locked))){new Notice('잠금을 해제한 뒤 병합해주세요.');return;}const ids=new Set(roots.flatMap(l=>[...descendants(this.d,l.id)]));const target=await this.s.anchors.mergeTarget(roots);if(target===undefined)return;await this.s.engine.load(this.d);const singleGroup=roots.length===1&&roots[0].type==='group';const tiles=singleGroup?this.s.engine.composite(this.d,roots[0].id):this.s.engine.composite(this.d,roots[0].parent,null,[],ids);this.change(()=>{const l=makeLayer(roots.length===1?roots[0].name:roots[0].name+' 병합','layer',roots[0].parent);l.anchor=target?clone(this.d.layers.find(n=>n.anchor?.targetId===target)?.anchor):null;if(singleGroup){l.opacity=roots[0].opacity;l.blend=roots[0].blend;l.visible=roots[0].visible;l.colorLabel=roots[0].colorLabel;}l.tiles=[...tiles.values()].map(t=>({x:t.x,y:t.y,png:t.c.toDataURL('image/png')}));const index=this.d.layers.indexOf(roots[0]);this.d.layers=this.d.layers.filter(n=>!ids.has(n.id));this.d.layers.splice(index,0,l);this.d.strokes=this.d.strokes.filter(s=>!ids.has(s.layerId));this.d.selectedLayers=[l.id];});await this.s.engine.load(this.d);this.s.scheduleRender();}
 menu(l,event){const m=new Menu();const add=(name,fn)=>m.addItem(i=>i.setTitle(name).onClick(fn));add('이름 바꾸기',()=>this.rename(l,this.s.layers.querySelector(`[data-layer-id="${l.id}"] .cdt-layer-name`)));add('복제',()=>this.duplicate());add('선택 항목 그룹으로 묶기',()=>this.group());if(l.type==='group')add('그룹 해제',()=>this.ungroup());add('선택 항목 병합',()=>this.merge());this.s.anchors?.menu(m,[...this.d.selectedLayers]);add('삭제',()=>this.remove());m.showAtMouseEvent(event);}
 render(){if(!this.s.record)return;const panel=this.s.layers;panel.replaceChildren();this.thumbs.clear();const heading=this.el('div','cdt-panel-heading',panel,'Drawing 레이어');this.icon(heading,'x','레이어 패널 닫기',()=>this.s.workspaceUI.toggle('layersCollapsed'));
  const props=this.el('div','cdt-layer-props',panel),l=this.current,blend=this.el('select','',props);blend.setAttribute('aria-label','레이어 합성 모드');blends.forEach((v,i)=>{const o=this.el('option','',blend,blendNames[i]);o.value=v;});blend.value=l?.blend||'source-over';blend.disabled=!l;blend.onchange=()=>this.change(()=>this.chosen.forEach(l=>l.blend=blend.value));
  const opacity=this.el('input','',props);opacity.type='range';opacity.min=0;opacity.max=100;opacity.value=(l?.opacity??1)*100;opacity.setAttribute('aria-label','레이어 불투명도');opacity.disabled=!l;opacity.oninput=()=>{for(const n of this.chosen)n.opacity=Number(opacity.value)/100;percent.value=opacity.value;this.s.scheduleRender();};opacity.onpointerdown=()=>{this.opacityBefore=snapshot(this.d);};const saveOpacity=()=>{if(!this.opacityBefore)return;this.s.record.history.push(this.opacityBefore);this.opacityBefore=null;this.s.plugin.store.changed(this.s.record);this.s.plugin.queueSave();};opacity.onpointerup=saveOpacity;opacity.onkeydown=()=>{this.opacityBefore??=snapshot(this.d);};opacity.onkeyup=saveOpacity;
  const percent=this.el('input','',props);percent.type='number';percent.min=0;percent.max=100;percent.value=opacity.value;percent.disabled=!l;percent.setAttribute('aria-label','레이어 불투명도 수치');percent.onchange=()=>this.change(()=>this.chosen.forEach(n=>n.opacity=Math.max(0,Math.min(100,Number(percent.value)))/100));
  const actions=this.el('div','cdt-row-actions',panel);for(const [key,ic,label]of [['locked','lock','잠금'],['alphaLock','scan','투명 부분 잠금'],['clip','layers-2','아래 레이어에 클립']]){const b=this.icon(actions,ic,label,()=>this.change(()=>{const value=!this.current?.[key];for(const l of this.chosen)if(key==='locked'||l.type==='layer')l[key]=value;}));require('./ui-actions').bind(this.s,b,'action:layer:'+key,label,()=>{if(this.current)this.change(()=>{const v=!this.current[key];for(const n of this.chosen)if(key==='locked'||n.type==='layer')n[key]=v})});b.disabled=!l||(key!=='locked'&&l.type!=='layer');b.setAttribute('aria-pressed',String(!!l?.[key]));b.classList.toggle('is-active',!!l?.[key]);}
  this.linkButton=this.icon(actions,this.s.anchors?.linked()?'unlink':'link',this.s.anchors?.linked()?'연결 해제':'Canvas에서 연결 대상 고르기',()=>this.s.anchors.toggle());
  require('./ui-actions').bind(this.s,this.linkButton,'action:anchor','Canvas 항목 연결 / 해제',()=>this.s.anchors.toggle());const solo=this.icon(actions,'focus','선택 레이어만 보기',()=>{this.solo=this.solo.length?[]:[...this.d.selectedLayers];this.render();this.s.scheduleRender();});require('./ui-actions').bind(this.s,solo,'action:layer:solo','선택 레이어만 보기',()=>solo.click());solo.setAttribute('aria-pressed',String(!!this.solo.length));solo.classList.toggle('is-active',!!this.solo.length);
  const colors=this.el('select','',actions);colors.setAttribute('aria-label','레이어 색 라벨');for(const [v,t]of [['','라벨 없음'],['red','빨강'],['yellow','노랑'],['green','초록'],['blue','파랑'],['purple','보라']]){const o=this.el('option','',colors,t);o.value=v;}colors.value=l?.colorLabel||'';colors.disabled=!l;colors.onchange=()=>this.change(()=>this.chosen.forEach(n=>n.colorLabel=colors.value));
  const search=this.el('input','cdt-layer-search',panel);search.placeholder='레이어 검색';search.value=this.search;search.setAttribute('aria-label','레이어 검색');search.oninput=()=>{this.revealed=null;this.search=search.value;this.listRender(list);};const filter=this.el('select','cdt-layer-filter',panel);filter.setAttribute('aria-label','레이어 필터');for(const [v,t]of [['all','전체'],['canvas','Canvas Drawing'],['anchor','Anchored Drawing'],['hidden','숨김'],['locked','잠금'],['color','현재 색 라벨']]){const o=this.el('option','',filter,t);o.value=v;}filter.value=this.filter;filter.onchange=()=>{this.revealed=null;this.filter=filter.value;this.label=this.current?.colorLabel||'';this.listRender(list);};
  const list=this.el('div','cdt-layer-list',panel);list.ondragover=e=>{if(this.drop&&e.dataTransfer.types.includes('application/cdt-layers'))e.preventDefault();};list.ondrop=e=>this.finishDrop(e);list.ondragleave=e=>{const r=list.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.clearDrop();};this.listRender(list);const foot=this.el('div','cdt-row-actions cdt-layer-footer',panel);for(const [ic,label,fn]of [['plus','레이어 추가',()=>this.add('layer')],['folder-plus','그룹 추가',()=>this.add('group')],['copy','레이어 복제',()=>this.duplicate()],['folder','선택 항목 그룹으로 묶기',()=>this.group()],['combine','선택 항목 병합',()=>this.merge()],['trash-2','레이어 삭제',()=>this.remove()]]){const b=this.icon(foot,ic,label,fn);b.disabled=!this.chosen.length&&!['레이어 추가','그룹 추가'].includes(label);if(ic==='trash-2')b.classList.add('cdt-danger');}this.el('p','cdt-hint',panel,'Ctrl: 여러 선택 · Shift: 범위 선택\n드래그: 순서 · 그룹 중앙에 놓기: 넣기\n이름 더블클릭: 이름 변경');
 }
 listRender(list){list.replaceChildren();this.thumbs.clear();this.rows=[];const query=this.search.toLowerCase();const walk=(parent,depth)=>{for(const l of this.d.layers.filter(l=>l.parent===parent)){const match=(!query||l.name.toLowerCase().includes(query))&&(this.filter==='all'||this.filter==='canvas'&&!l.anchor||this.filter==='anchor'&&!!l.anchor||this.filter==='hidden'&&!l.visible||this.filter==='locked'&&l.locked||this.filter==='color'&&l.colorLabel===this.label);if(match||this.revealed?.has(l.id)){this.rows.push(l);const row=this.el('div','cdt-layer-row'+(this.d.selectedLayers.includes(l.id)?' is-active':''),list);row.dataset.layerId=l.id;row.style.paddingLeft=(4+depth*14)+'px';row.style.borderLeftColor=l.colorLabel||'transparent';row.draggable=true;row.onclick=e=>{if(!e.target.closest('button,input'))this.select(l.id,e);};row.oncontextmenu=e=>{e.preventDefault();if(!this.d.selectedLayers.includes(l.id))this.select(l.id);this.menu(l,e);};
   const visibility=this.icon(row,l.visible?'eye':'eye-off',l.name+' 표시',()=>this.change(()=>l.visible=!l.visible));require('./ui-actions').bind(this.s,visibility,'action:layer:visible','선택 레이어 표시 / 숨김',()=>{if(this.current)this.change(()=>{const v=!this.current.visible;this.chosen.forEach(n=>n.visible=v)})});if(l.type==='group')this.icon(row,l.expanded?'chevron-down':'chevron-right',l.name+' 펼치기',()=>{l.expanded=!l.expanded;this.s.plugin.store.changed(this.s.record);this.s.plugin.queueSave();this.render();});const thumb=this.el('canvas','cdt-layer-thumb',row);thumb.width=104;thumb.height=80;this.thumbs.set(l.id,thumb);const body=this.el('div','cdt-layer-info',row),name=this.el('span','cdt-layer-name',body,l.name);name.ondblclick=e=>{e.stopPropagation();this.rename(l,name);};this.el('small','',body,`${Math.round(l.opacity*100)}% ${blendNames[blends.indexOf(l.blend)]}${l.locked?' · 잠금':''}${l.alphaLock?' · α':''}${l.clip?' · 클립':''}`);
   if(l.anchor){const target=this.el('button','cdt-anchor-name',body,'⚓ '+(this.s.anchors?.name(l.anchor.targetId)||'연결 대상'));target.title='연결된 Canvas 항목으로 이동';target.onclick=e=>{e.stopPropagation();this.s.anchors.focus(l.anchor.targetId);};}
   row.ondragstart=e=>{if(!this.d.selectedLayers.includes(l.id))this.select(l.id);this.dragIds=[...this.d.selectedLayers];e.dataTransfer.setData('application/cdt-layers',JSON.stringify(this.dragIds));e.dataTransfer.effectAllowed='all';row.classList.add('cdt-drag-source');};row.ondragover=e=>this.showDrop(row,l,e);row.ondrop=e=>this.finishDrop(e);row.ondragend=()=>{this.clearDrop();this.dragIds=null;row.classList.remove('cdt-drag-source');};}
   if(l.type==='group'&&(l.expanded||query||this.filter!=='all'))walk(l.id,depth+1);
  }};walk(null,0);this.refreshThumbnails();}
 refreshThumbnails(){for(const [id,c]of this.thumbs){const l=this.d.layers.find(l=>l.id===id);if(l)this.s.engine.thumbnail(c,l.type==='group'?this.s.engine.composite(this.d,l.id,this.s.active?.stroke.id):this.s.engine.leaf(this.d,l,this.s.active?.stroke.id));}}
}
module.exports={LayerUI};
