'use strict';
const {randomUUID}=require('./storage');
const {DrawingEngine,TILE}=require('./engine');
const {transform,translation}=require('./raster-edit');
const {RenderHistory}=require('./render-history');
const copy=x=>JSON.parse(JSON.stringify(x));
const blends=['source-over','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion','hue','saturation','color','luminosity'];
function makeLayer(name='Layer 1',type='layer',parent=null){return {id:randomUUID(),name,type,parent,visible:true,locked:false,opacity:1,blend:'source-over',alphaLock:false,clip:false,colorLabel:'',expanded:true,anchor:null,offset:{x:0,y:0},tiles:[]};}
function upgradeLayers(data){if(data.layers)return;data.layers=[];if(data.strokes.length){const l=makeLayer();data.layers.push(l);for(const s of data.strokes)s.layerId=l.id;data.selectedLayers=[l.id];}else data.selectedLayers=[];data.version=4;}
function descendants(data,id){const result=new Set([id]);let n;do{n=result.size;for(const l of data.layers)if(result.has(l.parent))result.add(l.id);}while(n!==result.size);return result;}
function ancestors(data,l){const a=[];while(l?.parent){l=data.layers.find(n=>n.id===l.parent);if(l)a.push(l);}return a;}
function writable(data,l){return l?.type==='layer'&&[l,...ancestors(data,l)].every(n=>n.visible&&!n.locked);}
const {snapshot,restore}=require('./history-state');
class LayerRenderer{
 constructor(make){this.make=make;this.engines=new Map();this.images=new Map();this.loading=new Map();this.tiles=new Map();this.history=new RenderHistory();this.identities=new WeakMap();this.nextIdentity=0;this.padding=new WeakMap();this.ink=new WeakMap();}
 async load(data){const urls=data.layers.flatMap(l=>l.tiles||[]).map(t=>t.png);await Promise.all(urls.map(url=>{if(this.images.has(url))return;if(!this.loading.has(url)){const img=this.make().ownerDocument.createElement('img');img.src=url;this.loading.set(url,img.decode().then(()=>{this.images.set(url,img);this.loading.delete(url);}).catch(error=>{this.loading.delete(url);throw error;}));}return this.loading.get(url);}));}

 leaf(data,l,activeId){if(this.overrides?.has(l.id))return this.overrides.get(l.id);let item=this.engines.get(l.id);const strokes=data.strokes.filter(s=>s.layerId===l.id);if(!item){item={engine:new DrawingEngine(this.make)};this.engines.set(l.id,item);}
  const changed=!item.list||item.list.length!==strokes.length||strokes.some((s,i)=>item.list[i]!==s)||item.raster!==l.tiles;
  const stable=!strokes.some(s=>s.id===activeId),key=stable?(changed||item.engine.current||item.engine.done!==strokes.length?this.stateKey(data,l,strokes):item.stateKey):null,cachedState=changed&&key&&this.history.get(key);
  item.assets=data.assets;item.stateKey=key;
  if(cachedState){item.generation=(item.generation||0)+1;item.list=strokes;item.raster=l.tiles;item.engine.seed=cachedState;item.engine.reset();item.engine.source=item.list;item.engine.done=strokes.length;}else if(changed&&item.list&&item.raster===l.tiles&&item.engine.done<=strokes.length&&item.list.slice(0,item.engine.done).every((s,i)=>s===strokes[i])){
   // Preserve committed paint while replacing only an uncommitted shape preview.
   if(item.engine.current?.s!==strokes[item.engine.done])item.engine.current=null;
   item.list.splice(0,item.list.length,...strokes);item.generation=(item.generation||0)+1;
  }else if(changed){item.generation=(item.generation||0)+1;item.list=strokes;item.source=data.strokes;item.raster=l.tiles;const seed=new Map();for(const t of l.tiles||[]){const img=this.images.get(t.png);if(img){const c=this.make();c.width=c.height=TILE;c.getContext('2d').drawImage(img,0,0);seed.set(t.x+','+t.y,{x:t.x,y:t.y,c,ctx:c.getContext('2d')});}}item.engine.seed=seed;item.engine.reset();}
  item.engine.assets=data.assets||{};item.engine.sync(item.list,activeId);const signature=[item.generation,item.engine.done,item.engine.current?.seen||0,l.offset?.x||0,l.offset?.y||0].join(',');if(item.output&&item.outputList===item.list&&item.outputSignature===signature)return item.output;const out=new Map();item.tileCache??=new Map();for(const key of new Set([...item.engine.tiles.keys(),...(item.engine.current?.tiles.keys()||[])])){const base=item.engine.tiles.get(key),over=item.engine.current?.tiles.get(key),tileKey=[base,base?.revision,over,over?.revision||0,over?item.engine.current.s:null];const cached=item.tileCache.get(key);if(cached&&tileKey.every((v,i)=>v===cached.key[i])){out.set(key,cached.tile);continue;}const t=base||over,c=this.make();c.width=c.height=TILE;const ctx=c.getContext('2d');ctx.translate(-t.x*TILE,-t.y*TILE);item.engine.renderTile(ctx,key);const tile={x:t.x,y:t.y,c};out.set(key,tile);item.tileCache.set(key,{key:tileKey,tile});}for(const key of item.tileCache.keys())if(!out.has(key))item.tileCache.delete(key);if(key&&!item.engine.current)this.history.put(key,out);item.output=l.offset&&(l.offset.x||l.offset.y)?transform(this.make,out,translation(l.offset.x,l.offset.y)):out;item.outputList=item.list;item.outputSignature=signature;return item.output;
 }
 composite(data,parent=null,activeId=null,solo=[],only=null,backdrop=null){const out=new Map(),commands=new Map();let base=null;const allowed=new Set(solo.flatMap(id=>[...descendants(data,id)]));for(const id of solo){const l=data.layers.find(n=>n.id===id);if(l)for(const a of ancestors(data,l))allowed.add(a.id);}
  for(const l of data.layers.filter(l=>l.parent===parent).slice().reverse()){
   if(solo.length?!allowed.has(l.id):!l.visible)continue;
   let tiles=l.type==='group'?this.composite(data,l.id,activeId,solo,only):this.leaf(data,l,activeId);
   if(l.clip){const clipped=new Map();if(base)for(const [key,t]of tiles){const mask=base.get(key);if(!mask)continue;const c=this.make();c.width=c.height=TILE;const ctx=c.getContext('2d');ctx.drawImage(t.c,0,0);ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask.c,0,0);clipped.set(key,{...t,c});}tiles=clipped;}else base=tiles;
   if(only&&!only.has(l.id)&&l.type!=='group')continue;
   for(const [key,t]of tiles){if(!commands.has(key))commands.set(key,[]);commands.get(key).push([t,l.opacity,l.blend]);}

  }
  this.compositeCache??=new Map();const cacheId=(parent||'root')+(backdrop?'paper':'raw'),previous=this.compositeCache.get(cacheId),next=new Map();
  for(const[key,list]of commands){const signature=[backdrop?.key,...list.flat()],old=previous?.get(key);if(old&&signature.every((v,i)=>v===old.signature[i])&&signature.length===old.signature.length){out.set(key,old.tile);next.set(key,old);continue;}const t=list[0][0],c=this.make();c.width=c.height=TILE;const ctx=c.getContext('2d',{willReadFrequently:true});if(backdrop&&parent===null)backdrop(ctx,t.x*TILE,t.y*TILE,TILE);for(const[tile,opacity,blend]of list){ctx.globalAlpha=opacity;ctx.globalCompositeOperation=blend;ctx.drawImage(tile.c,0,0);}const tile={x:t.x,y:t.y,c};out.set(key,tile);next.set(key,{signature,tile});}this.compositeCache.set(cacheId,next);return out;
 }
 sync(data,activeId=null,solo=[],backdrop=null){this.prune(data);if(!data.layers.some(l=>l.blend!=='source-over'))backdrop=null;const key=[data,data.revision,data.strokes,data.layers,activeId,data.strokes.at(-1)?.points?.length,this.overrides,JSON.stringify(solo),backdrop?.key,this.images.size];if(this.syncKey&&key.every((v,i)=>v===this.syncKey[i]))return;this.syncKey=key;this.tiles=this.composite(data,null,activeId,solo);this.displayTiles=backdrop?this.composite(data,null,activeId,solo,null,backdrop):this.tiles;if(backdrop){this.paperTileCache??=new Map();const next=new Map(),display=new Map();for(const[key,t]of this.displayTiles){const rawTile=this.tiles.get(key),old=this.paperTileCache.get(key);if(old?.source===t&&old.raw===rawTile&&old.paperKey===backdrop.key){display.set(key,old.tile);next.set(key,old);continue;}const out=t.c.getContext('2d').getImageData(0,0,TILE,TILE),raw=rawTile.c.getContext('2d').getImageData(0,0,TILE,TILE);let bg=old?.paperKey===backdrop.key?old.bg:null;if(!bg){const paper=this.make();paper.width=paper.height=TILE;const pc=paper.getContext('2d',{willReadFrequently:true});backdrop(pc,t.x*TILE,t.y*TILE,TILE);bg=pc.getImageData(0,0,TILE,TILE);}for(let i=0;i<out.data.length;i+=4){const a=raw.data[i+3]/255;out.data[i+3]=raw.data[i+3];for(let j=0;j<3;j++)out.data[i+j]=a?(out.data[i+j]-bg.data[i+j]*(1-a))/a:0;}const c=this.make();c.width=c.height=TILE;c.getContext('2d').putImageData(out,0,0);const tile={x:t.x,y:t.y,c};display.set(key,tile);next.set(key,{source:t,raw:rawTile,paperKey:backdrop.key,bg,tile});}this.paperTileCache=next;this.displayTiles=display;}}

 id(object){if(!object||typeof object!=='object')return String(object);let id=this.identities.get(object);if(!id){id=++this.nextIdentity;this.identities.set(object,id);}return id;}
 stateKey(data,l,strokes){return [this.id(l.tiles),...strokes.map(s=>this.id(s)),...Object.keys(data.assets||{}).sort()].join(':');}
 render(ctx,bounds){const tiles=this.displayTiles||this.tiles,m=ctx.getTransform();for(const t of tiles.values()){const x=t.x*TILE,y=t.y*TILE;if(bounds&&(x+TILE<bounds.left||x>bounds.right||y+TILE<bounds.top||y>bounds.bottom))continue;
  const pad=Math.max(1,Math.ceil(2/Math.min(m.a,m.d))),neighbors=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)neighbors.push(tiles.get((t.x+dx)+','+(t.y+dy)));
  let cache=this.padding.get(t);if(!cache||cache.pad!==pad||neighbors.some((n,i)=>n!==cache.neighbors[i])){const c=this.make();c.width=c.height=TILE+pad*2;const pc=c.getContext('2d');neighbors.forEach((n,i)=>{if(n)pc.drawImage(n.c,pad+(i%3-1)*TILE,pad+(Math.floor(i/3)-1)*TILE)});cache={pad,neighbors,c};this.padding.set(t,cache);}
  const left=Math.round(x*m.a+m.e),top=Math.round(y*m.d+m.f),right=Math.round((x+TILE)*m.a+m.e),bottom=Math.round((y+TILE)*m.d+m.f);ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.beginPath();ctx.rect(left,top,right-left,bottom-top);ctx.clip();ctx.setTransform(m);ctx.drawImage(cache.c,x-pad,y-pad);ctx.restore();}}
 dispose(){this.engines.clear();this.images.clear();this.loading.clear();this.tiles.clear();this.history.entries.clear();this.history.bytes=0;this.compositeCache?.clear();this.padding=new WeakMap();this.ink=new WeakMap();this.displayTiles=null;}
 prune(data){const ids=new Set(data.layers.map(l=>l.id));for(const id of this.engines.keys())if(!ids.has(id))this.engines.delete(id);}

 sample(x,y){const tx=Math.floor(x/TILE),ty=Math.floor(y/TILE);return Array.from(this.tiles.get(tx+','+ty)?.c.getContext('2d').getImageData(Math.floor(x-tx*TILE),Math.floor(y-ty*TILE),1,1).data||[0,0,0,0]);}
 thumbnail(canvas,tiles){this.thumbCache??=new WeakMap();const cached=this.thumbCache.get(canvas);if(cached?.tiles===tiles&&cached.width===canvas.width&&cached.height===canvas.height)return;this.thumbCache.set(canvas,{tiles,width:canvas.width,height:canvas.height});const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);let left=Infinity,top=Infinity,right=-Infinity,bottom=-Infinity;for(const t of tiles.values()){let b=this.ink.get(t);if(!b){b={left:Infinity,top:Infinity,right:-Infinity,bottom:-Infinity};const a=t.c.getContext('2d').getImageData(0,0,TILE,TILE).data;for(let y=0;y<TILE;y++)for(let x=0;x<TILE;x++)if(a[(y*TILE+x)*4+3]){b.left=Math.min(b.left,x);b.right=Math.max(b.right,x+1);b.top=Math.min(b.top,y);b.bottom=Math.max(b.bottom,y+1);}this.ink.set(t,b);}left=Math.min(left,t.x*TILE+b.left);right=Math.max(right,t.x*TILE+b.right);top=Math.min(top,t.y*TILE+b.top);bottom=Math.max(bottom,t.y*TILE+b.bottom);}if(!Number.isFinite(left))return;const w=right-left,h=bottom-top,scale=Math.min((canvas.width-8)/Math.max(w,1),(canvas.height-8)/Math.max(h,1));ctx.save();ctx.translate((canvas.width-w*scale)/2,(canvas.height-h*scale)/2);ctx.scale(scale,scale);for(const t of tiles.values())ctx.drawImage(t.c,t.x*TILE-left,t.y*TILE-top);ctx.restore();}
}
module.exports={blends,makeLayer,upgradeLayers,descendants,ancestors,writable,snapshot,restore,LayerRenderer};


