'use strict';
const {Notice}=require('obsidian');
const {clone,preset}=require('./brush');
const {asset,modes,repeats}=require('./materials');
const {parseABR}=require('./abr');
class MaterialUI{
 constructor(ui){this.u=ui;this.s=ui.s;}
 thumb(parent,a){const u=this.u,c=u.el('canvas','cdt-material-thumb',parent);c.width=a.width;c.height=a.height;const cx=c.getContext('2d'),im=cx.createImageData(a.width,a.height),bytes=Buffer.from(a.mask,'base64');for(let i=0;i<bytes.length;i++){const v=a.kind==='tip'?230:bytes[i];im.data[i*4]=im.data[i*4+1]=im.data[i*4+2]=v;im.data[i*4+3]=a.kind==='tip'?bytes[i]:255;}cx.putImageData(im,0,0);return c;}
 tip(body,refresh){const u=this.u,p=u.p;u.select(body,'끝 모양',p,'tipType',[['circle','원형'],['custom','소재']]).addEventListener('change',refresh);if(p.tipType==='custom'){const list=u.el('div','cdt-material-list',body);p.tips.forEach((a,i)=>{const row=u.el('div','cdt-material-row',list);row.draggable=true;row.dataset.tipIndex=i;row.ondragstart=e=>{this.dragIndex=i;e.dataTransfer.setData('text/plain',String(i));e.dataTransfer.effectAllowed='move';};row.ondragover=e=>{if(this.dragIndex!==undefined){e.preventDefault();row.classList.add('cdt-material-drop');}};row.ondragleave=()=>row.classList.remove('cdt-material-drop');row.ondragend=()=>{this.dragIndex=undefined;row.classList.remove('cdt-material-drop');};row.ondrop=e=>{e.preventDefault();const from=this.dragIndex;this.dragIndex=undefined;if(from===undefined||from===i)return;const a=p.tips.splice(from,1)[0];p.tips.splice(i,0,a);u.save();refresh();};this.thumb(row,a);u.el('span','',row,a.name);const move=delta=>{const j=i+delta;if(j<0||j>=p.tips.length)return;[p.tips[i],p.tips[j]]=[p.tips[j],p.tips[i]];u.save();refresh();};u.icon(row,'chevron-up',a.name+' 앞으로',()=>move(-1));u.icon(row,'chevron-down',a.name+' 뒤로',()=>move(1));u.icon(row,'library',a.name+' 라이브러리에 등록',()=>this.register(a));u.icon(row,'x',a.name+' 끝에서 제거',()=>{p.tips.splice(i,1);u.save();refresh();});});u.btn(body,'＋ 끝 소재 추가',()=>this.library('tip',a=>{p.tips.push(clone(a));u.save();refresh();}));this.fileInput(body,'끝 이미지 가져오기','image/png,image/jpeg,image/webp',async f=>{const a=await this.readImage(f,'tip');this.register(a,false);p.tips.push(a);u.save();refresh();});u.select(body,'소재 반복 방법',p,'tipRepeat',repeats);if(!p.tips.length)u.el('p','cdt-hint',body,'끝 소재를 추가하세요.');}else u.field(body,'hardness',true);for(const k of ['roundness','angle','tipScale','density'])u.field(body,k,true);u.exposedCheck(body,'좌우 반전','flipX',true);u.exposedCheck(body,'상하 반전','flipY',true);u.check(body,'기울기 → 끝 모양 각도',p,'tilt');}
 texture(body,refresh){const u=this.u,p=u.p;u.exposedCheck(body,'종이 재질 사용','texture',true);if(p.textureAsset){const row=u.el('div','cdt-material-row',body);this.thumb(row,p.textureAsset);u.el('span','',row,p.textureAsset.name);u.icon(row,'library','현재 재질 라이브러리에 등록',()=>this.register(p.textureAsset));u.icon(row,'x','선택한 종이 소재 해제',()=>{p.textureAsset=null;p.texture=false;u.save();refresh();});}else u.el('p','cdt-no-texture',body,'소재 없음');u.btn(body,'종이 재질 소재 선택',()=>this.library('texture',a=>{p.textureAsset=clone(a);p.texture=true;u.save();refresh();}));this.fileInput(body,'재질 이미지 가져오기','image/png,image/jpeg,image/webp',async f=>{const a=await this.readImage(f,'texture');this.register(a,false);p.textureAsset=a;p.texture=true;u.save();refresh();});for(const k of ['textureDensity','textureScale','textureAngle'])u.field(body,k,true);u.select(body,'종이 재질 적용 방법',p,'textureMode',modes);u.exposedCheck(body,'점별로 적용','textureEachPlot',true);u.el('p','cdt-hint',body,'점별로 적용: 끝 모양마다 재질을 적용해 겹침을 쌓습니다. 끄면 획 전체에 적용합니다.');}
 register(a,notice=true){const list=this.u.plugin.settings.library;if(!list.some(b=>b.id===a.id)){list.push(clone(a));if(notice)this.u.save();}if(notice)new Notice('라이브러리에 등록했습니다.');}
 library(kind='tip',pick){const u=this.u,m=u.modal(kind==='tip'?'브러시 끝 소재':'종이 재질 소재','cdt-library-dialog');const render=()=>{m.contentEl.replaceChildren();const list=u.el('div','cdt-material-list',m.contentEl);for(const a of u.plugin.settings.library.filter(a=>a.kind===kind)){const row=u.el('div','cdt-material-row',list);this.thumb(row,a);u.el('span','',row,a.name);if(pick)u.btn(row,'선택',()=>{pick(a);m.close();});u.icon(row,'pencil','소재 이름 변경: '+a.name,()=>u.nameDialog('소재 이름',a.name,name=>{a.name=name;u.save();render();}));u.icon(row,'trash-2','소재 삭제: '+a.name,()=>u.confirm('라이브러리에서 삭제할까요? 사용 중인 브러시와 그림은 유지됩니다.',()=>{u.plugin.settings.library=u.plugin.settings.library.filter(b=>b!==a);u.save();render();})).classList.add('cdt-danger');}this.fileInput(m.contentEl,'이미지 가져오기','image/png,image/jpeg,image/webp',async f=>{this.register(await this.readImage(f,kind),false);u.save();render();});u.el('p','cdt-hint',m.contentEl,'PNG/JPG/WebP · 최대 16MB · 긴 변 512px로 변환\n끝 소재는 어두운 부분이 칠해집니다. 투명도도 반영합니다.\n라이브러리 삭제는 이미 사용한 소재를 바꾸지 않습니다.');u.btn(m.contentEl,kind==='tip'?'종이 재질 목록':'끝 소재 목록',()=>{m.close();this.library(kind==='tip'?'texture':'tip');});u.btn(m.contentEl,'닫기',()=>m.close());};render();}
 fileInput(parent,label,accept,action){const u=this.u,row=u.el('label','cdt-import-file',parent,label),input=u.el('input','',row);input.type='file';input.accept=accept;input.setAttribute('aria-label',label);input.onchange=async()=>{if(!input.files[0])return;try{await action(input.files[0]);}catch(e){new Notice('가져오기 실패: '+e.message);}finally{input.value='';}};return input;}
 async readImage(file,kind){if(file.size>16*1024*1024)throw Error('16MB 이하 이미지를 선택하세요.');const img=this.s.doc.createElement('img'),url=URL.createObjectURL(file);try{img.src=url;await img.decode();if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>40000000)throw Error('이미지 크기 제한 초과');const scale=Math.min(1,512/Math.max(img.naturalWidth,img.naturalHeight)),c=this.s.doc.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);const rgba=ctx.getImageData(0,0,c.width,c.height).data,out=Buffer.alloc(c.width*c.height);for(let i=0;i<out.length;i++){const j=i*4,l=(rgba[j]*.2126+rgba[j+1]*.7152+rgba[j+2]*.0722),a=rgba[j+3]/255;out[i]=Math.round(kind==='tip'?(255-l)*a:l*a+255*(1-a));}return asset(kind,file.name.replace(/\.[^.]+$/,'').slice(0,200),c.width,c.height,out);}finally{URL.revokeObjectURL(url);}}
 abr(){const u=this.u,m=u.modal('ABR 가져오기');u.el('p','cdt-hint',m.contentEl,'ABR 1/2, 6/10(하위 형식 1/2)의 8비트 샘플 끝 · Raw/RLE\n계산형·16비트·Photoshop 동적 속성은 지원하지 않습니다.\n끝 소재는 긴 변 512px까지 보관합니다. 최대 64MB.');this.fileInput(m.contentEl,'ABR 파일','.abr',async file=>{if(file.size>64*1024*1024)throw Error('64MB 제한');const r=parseABR(await file.arrayBuffer(),file.name.replace(/\.abr$/i,''));for(const item of r.brushes){this.register(item.asset,false);const p=preset(crypto.randomUUID(),item.asset.name,'brush',{size:item.size,spacing:item.spacing,tipType:'custom',tips:[item.asset]});p.group='ABR';p.defaults=clone(Object.fromEntries(Object.entries(p).filter(([k])=>!['id','name','tool','defaults'].includes(k))));u.plugin.settings.presets.push(p);}u.save();if(['brush','eraser'].includes(this.s.tool))u.render();const result=u.el('div','cdt-import-result',m.contentEl);result.setAttribute('role','status');u.el('h3','',result,`${r.brushes.length}개 브러시 추가 · ${r.skipped.length}개 제외/오류`);for(const text of [...r.notes,...r.skipped])u.el('p','cdt-hint',result,text);this.lastABR=r;});u.btn(m.contentEl,'닫기',()=>m.close());}
}
module.exports={MaterialUI};
