'use strict';
const {createHash}=require('node:crypto');
const modes=[['normal','보통'],['multiply','곱하기'],['subtract','감산'],['compare','비교'],['outline','윤곽'],['overlay','오버레이'],['dodge','색상 닷지'],['hardmix','하드 믹스'],['height','높이']];
const repeats=[['repeat','순서대로 반복'],['reverse','왕복'],['last','마지막 소재 계속'],['random','무작위'],['once','한 번만'],['random-once','무작위로 한 번만']];
const materialDefaults={tipType:'circle',tips:[],tipRepeat:'repeat',tipScale:1,flipX:false,flipY:false,texture:false,textureAsset:null,textureDensity:.7,textureScale:1,textureAngle:0,textureMode:'multiply',textureEachPlot:false};
const clamp=x=>Math.max(0,Math.min(1,x));
function asset(kind,name,width,height,bytes){const mask=Buffer.from(bytes).toString('base64'),id=createHash('sha256').update(`${kind}:${width}:${height}:${mask}`).digest('hex');return {id,kind,name,width,height,mask};}
function validAsset(a){return !!a&&['tip','texture'].includes(a.kind)&&typeof a.name==='string'&&a.name.length<=200&&Number.isInteger(a.width)&&Number.isInteger(a.height)&&a.width>0&&a.height>0&&a.width<=512&&a.height<=512&&typeof a.mask==='string'&&a.mask.length<=350000&&/^[A-Za-z0-9+/]*={0,2}$/.test(a.mask)&&Buffer.from(a.mask,'base64').length===a.width*a.height&&a.id===asset(a.kind,a.name,a.width,a.height,Buffer.from(a.mask,'base64')).id;}
function normalizeMask(kind,name,w,h,bytes){const scale=Math.min(1,512/Math.max(w,h)),width=Math.max(1,Math.round(w*scale)),height=Math.max(1,Math.round(h*scale)),out=Buffer.alloc(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++)out[y*width+x]=bytes[Math.min(h-1,Math.floor(y/scale))*w+Math.min(w-1,Math.floor(x/scale))];return asset(kind,name.slice(0,200),width,height,out);}
function builtins(){const n=64,leaf=Buffer.alloc(n*n),grain=Buffer.alloc(n*n);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const u=(x+0.5)/n*2-1,v=(y+0.5)/n*2-1;leaf[y*n+x]=Math.abs(u)<.48*Math.sin((v+1)*Math.PI/2)?255:0;const noise=Math.sin(x*127.1+y*311.7)*43758.5453;grain[y*n+x]=Math.round(55+(noise-Math.floor(noise))*185);}return [asset('tip','나뭇잎',n,n,leaf),asset('texture','종이 결',n,n,grain)];}
function tipIndex(index,count,mode,seed=0){if(!count)return -1;if(mode==='once')return index<count?index:-1;if(mode==='last')return Math.min(index,count-1);if(mode==='reverse'){const t=index%Math.max(1,count*2-2);return t<count?t:count*2-2-t;}if(mode==='random'||mode==='random-once'){const order=Array.from({length:count},(_,i)=>i);const rand=n=>{const v=Math.sin((n+1)*127.1+seed*311.7)*43758.5453;return v-Math.floor(v);};if(mode==='random')return Math.floor(rand(index)*count);if(index>=count)return -1;for(let i=count-1;i>0;i--){const j=Math.floor(rand(i)*(i+1));[order[i],order[j]]=[order[j],order[i]];}return order[index];}return index%count;}
function freezeMaterials(p,data){data.assets??={};const copy={...p};copy.tips=(p.tips||[]).map(a=>{data.assets[a.id]??=a;return a.id;});if(p.textureAsset){data.assets[p.textureAsset.id]??=p.textureAsset;copy.textureAsset=p.textureAsset.id;}return copy;}
function resolveAsset(a,assets){return typeof a==='string'?assets?.[a]:a;}
function packMaterials(value){const catalog={};const walk=v=>{if(!v||typeof v!=='object')return v;if(v.mask&&v.id&&['tip','texture'].includes(v.kind)){catalog[v.id]??=v;return{materialRef:v.id,name:v.name};}if(Array.isArray(v))return v.map(walk);return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,walk(x)]));};return{...walk(value),materialCatalog:catalog,materialEncoding:1};}
function unpackMaterials(value){if(value?.materialEncoding!==1)return value;const catalog=value.materialCatalog;if(!catalog||typeof catalog!=='object')throw Error('소재 목록이 없습니다.');const valid={};for(const[id,a]of Object.entries(catalog))if(validAsset(a)&&id===a.id)valid[id]=a;const walk=v=>{if(!v||typeof v!=='object')return v;if(typeof v.materialRef==='string'){const a=valid[v.materialRef];return a?{...a,name:typeof v.name==='string'?v.name.slice(0,200):a.name}:{id:v.materialRef,missing:true};}if(Array.isArray(v))return v.map(walk);return Object.fromEntries(Object.entries(v).filter(([k])=>!['materialCatalog','materialEncoding'].includes(k)).map(([k,x])=>[k,walk(x)]));};return walk(value);}
// A paper material changes paint coverage, never introduces black RGB fringes.
function coverage(alpha,grain,strength,mode){let v;switch(mode){case'normal':v=Math.min(alpha,grain);break;case'subtract':v=Math.max(0,alpha+grain-1);break;case'compare':v=alpha>=1-grain?alpha:0;break;case'outline':v=alpha+(grain-.5)*4*alpha*(1-alpha);break;case'overlay':v=alpha<.5?2*alpha*grain:1-2*(1-alpha)*(1-grain);break;case'dodge':v=Math.min(1,alpha/Math.max(.01,1-grain));break;case'hardmix':v=alpha+grain>=1?1:0;break;case'height':v=alpha>=1?1:clamp((alpha-(1-grain))/.25);break;default:v=alpha*grain;}return alpha===0?0:clamp(alpha+(clamp(v)-alpha)*strength);}
const decodedMasks=new WeakMap();
function applyTexture(canvas,s,a,originX=0,originY=0){if(!a||!s.texture)return canvas;const ctx=canvas.getContext('2d'),im=ctx.getImageData(0,0,canvas.width,canvas.height),bytes=decodedMasks.get(a)||Buffer.from(a.mask,'base64'),angle=(s.textureAngle||0)*Math.PI/180,c=Math.cos(angle),t=Math.sin(angle),scale=s.textureScale||1;decodedMasks.set(a,bytes);for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4;if(!im.data[i+3])continue;const u=x+originX,v=y+originY,tx=((Math.floor((u*c+v*t)/scale)%a.width)+a.width)%a.width,ty=((Math.floor((-u*t+v*c)/scale)%a.height)+a.height)%a.height;im.data[i+3]=Math.round(255*coverage(im.data[i+3]/255,bytes[ty*a.width+tx]/255,s.textureDensity??.7,s.textureMode));}ctx.putImageData(im,0,0);return canvas;}
module.exports={asset,validAsset,normalizeMask,builtins,materialDefaults,modes,repeats,tipIndex,freezeMaterials,resolveAsset,coverage,applyTexture,packMaterials,unpackMaterials};
