'use strict';
function floating(s,box,key){
 box.classList.add('cdt-floating');box.dataset.panel=key;let drag=null;
 const handles=[];const sync=()=>{const r=box.getBoundingClientRect(),h=s.host.getBoundingClientRect(),x=r.left-h.left,y=r.top-h.top,w=r.width,v=r.height;for(const el of handles){el.hidden=box.hidden||!w||!v;const side=el.dataset.side,corner=side.length===2;Object.assign(el.style,{left:(x+(side.includes('w')?-3:side.includes('e')?w-4:4))+'px',top:(y+(side.includes('n')?-3:side.includes('s')?v-4:4))+'px',width:(corner||side==='w'||side==='e'?8:Math.max(0,w-8))+'px',height:(corner||side==='n'||side==='s'?8:Math.max(0,v-8))+'px'});}};
 const apply=()=>{const p=s.plugin.settings.panelPositions?.[key];if(p){const r=s.host.getBoundingClientRect();Object.assign(box.style,{left:Math.max(0,Math.min(p.x,r.width-80))+'px',top:Math.max(0,Math.min(p.y,r.height-40))+'px',right:'auto',width:p.width+'px',height:p.height+'px'});}sync();};
 const save=()=>{const r=box.getBoundingClientRect(),h=s.host.getBoundingClientRect();if(!r.width||!r.height)return;const value={x:r.left-h.left,y:r.top-h.top,width:r.width,height:r.height};s.plugin.settings.panelPositions??={};if(JSON.stringify(s.plugin.settings.panelPositions[key])!==JSON.stringify(value)){s.plugin.settings.panelPositions[key]=value;s.plugin.saveData(s.plugin.settings);}sync();};
 for(const side of ['n','s','w','e','nw','ne','sw','se']){const el=s.element('div','cdt-panel-edge',s.host);el.dataset.side=side;el.dataset.panelEdge=key;el.style.cursor=side==='n'||side==='s'?'ns-resize':side==='e'||side==='w'?'ew-resize':side==='nw'||side==='se'?'nwse-resize':'nesw-resize';handles.push(el);s.listen(el,'pointerdown',e=>{if(e.button!==0)return;const r=box.getBoundingClientRect(),h=s.host.getBoundingClientRect();drag={id:e.pointerId,side,x:e.clientX,y:e.clientY,left:r.left-h.left,top:r.top-h.top,width:r.width,height:r.height,el};el.setPointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation();});s.listen(el,'pointermove',e=>{if(drag?.id!==e.pointerId)return;const d=drag,h=s.host.getBoundingClientRect(),dx=e.clientX-d.x,dy=e.clientY-d.y,w=Math.min(h.width-20,Math.max(240,d.width+(side.includes('w')?-dx:side.includes('e')?dx:0))),v=Math.min(h.height-20,Math.max(220,d.height+(side.includes('n')?-dy:side.includes('s')?dy:0)));Object.assign(box.style,{right:'auto',width:w+'px',height:v+'px',left:Math.max(0,d.left+(side.includes('w')?d.width-w:0))+'px',top:Math.max(0,d.top+(side.includes('n')?d.height-v:0))+'px'});sync();e.preventDefault();e.stopImmediatePropagation();});s.listen(el,'pointerup',e=>{if(drag?.id!==e.pointerId)return;el.releasePointerCapture(e.pointerId);drag=null;save();e.stopImmediatePropagation();});s.listen(el,'pointercancel',()=>{drag=null;});}
 s.listen(box,'pointerdown',e=>{if(e.button!==0||e.target.closest('button,input,select')||!e.target.closest('.cdt-color-head,.cdt-panel-heading'))return;const r=box.getBoundingClientRect(),h=s.host.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left-h.left,top:r.top-h.top};box.setPointerCapture(e.pointerId);e.preventDefault();e.stopPropagation();});
 s.listen(box,'pointermove',e=>{if(drag?.id!==e.pointerId||drag.side)return;const h=s.host.getBoundingClientRect();Object.assign(box.style,{right:'auto',left:Math.max(0,Math.min(h.width-80,drag.left+e.clientX-drag.x))+'px',top:Math.max(0,Math.min(h.height-40,drag.top+e.clientY-drag.y))+'px'});sync();});
 s.listen(box,'pointerup',e=>{if(drag?.id===e.pointerId){if(box.hasPointerCapture(e.pointerId))box.releasePointerCapture(e.pointerId);drag=null;}save();});s.listen(box,'pointercancel',()=>{drag=null;});
 const resize=new s.win.ResizeObserver(sync),mut=new s.win.MutationObserver(sync);resize.observe(box);resize.observe(s.host);mut.observe(box,{attributes:true,attributeFilter:['style','hidden']});s.listeners.push(()=>{resize.disconnect();mut.disconnect();handles.forEach(el=>el.remove())});apply();return {apply,save};
}
function split(s,panel,list,key){const q=s.plugin.settings;q.listHeights??={};const bar=s.element('div','cdt-list-splitter',panel);bar.setAttribute('role','separator');bar.setAttribute('aria-label','도구 목록 높이 조절');bar.setAttribute('aria-orientation','horizontal');bar.tabIndex=0;let drag;
 const set=v=>{v=Math.max(65,Math.min(Math.max(100,s.host.clientHeight-180),v));list.style.maxHeight='none';list.style.height=v+'px';q.listHeights[key]=v;bar.setAttribute('aria-valuenow',String(Math.round(v)));};set(q.listHeights[key]||240);
 bar.onpointerdown=e=>{e.preventDefault();e.stopPropagation();drag={y:e.clientY,h:list.offsetHeight,id:e.pointerId};bar.setPointerCapture(e.pointerId);};bar.onpointermove=e=>{if(drag?.id===e.pointerId)set(drag.h+e.clientY-drag.y);};bar.onpointerup=e=>{if(!drag)return;drag=null;bar.releasePointerCapture(e.pointerId);s.plugin.saveData(q);};bar.onpointercancel=()=>{drag=null};bar.onkeydown=e=>{if(!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();set(list.offsetHeight+(e.key==='ArrowDown'?20:-20));s.plugin.saveData(q);};return bar;
}
module.exports={floating,split};
