'use strict';
const {Modal,Notice}=require('obsidian');
const {snapshot}=require('./layers');
const defaults=()=>({enabled:false,preset:'plain',color:'#fffdf6',strength:30,size:100,image:''});
const presets={plain:'매끈한 종이',fine:'고운 종이',rough:'거친 종이',watercolor:'수채화 용지',kraft:'크라프트지',custom:'사용자 이미지'};
class PaperUI{
 constructor(s){this.s=s;this.cache=new Map();this.original=s.host.style.background;}
 texture(p){if(p.preset==='plain')return '';const key=[p.preset,p.strength,p.image].join('|');if(this.cache.has(key))return this.cache.get(key);const c=this.s.doc.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');let seed=73821;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  if(p.preset==='custom'){const img=this.images?.get(p.image);if(!img)return '';ctx.globalAlpha=p.strength/100;ctx.drawImage(img,0,0,256,256);}
  else{const image=ctx.createImageData(256,256),noise=Array.from({length:4096},random);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const i=(y*256+x)*4,grain=p.preset==='watercolor'?noise[(Math.floor(y/4)*64+Math.floor(x/4))%4096]*.65+random()*.35:random(),dark=grain>.5;image.data[i]=image.data[i+1]=image.data[i+2]=dark?75:255;image.data[i+3]=Math.abs(grain-.5)*2*p.strength*(p.preset==='fine'?.65:1.5);}ctx.putImageData(image,0,0);if(p.preset==='rough'||p.preset==='kraft'){ctx.strokeStyle=`rgba(85,65,40,${p.strength/500})`;for(let i=0;i<900;i++){const x=random()*256,y=random()*256;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+random()*9,y+random()*2);ctx.stroke();}}}
  if(p.preset==='watercolor'){const smooth=this.s.doc.createElement('canvas');smooth.width=smooth.height=256;const sc=smooth.getContext('2d');sc.filter='blur(1.2px)';sc.drawImage(c,0,0);ctx.clearRect(0,0,256,256);ctx.drawImage(smooth,0,0);}
  this.textureCanvases??=new Map();this.textureCanvases.set(key,c);const url=c.toDataURL();if(this.cache.size>12)this.cache.clear();this.cache.set(key,url);return url;
 }
 backdrop(){const p=this.draft||this.s.record?.data.paper;if(!p?.enabled)return null;this.texture(p);const texture=this.textureCanvases?.get([p.preset,p.strength,p.image].join('|'));const draw=(ctx,x,y,size)=>{ctx.fillStyle=p.color;ctx.fillRect(0,0,size,size);if(texture){ctx.save();ctx.translate(-x,-y);ctx.scale(p.size/100,p.size/100);ctx.fillStyle=ctx.createPattern(texture,'repeat');ctx.fillRect(x*100/p.size,y*100/p.size,size*100/p.size,size*100/p.size);ctx.restore();}};draw.key=JSON.stringify([p.preset,p.strength,p.image,p.color,p.size,!!texture]);return draw;}
 async loadImage(url){if(!url)return;this.images??=new Map();if(this.images.has(url))return;const img=this.s.doc.createElement('img');img.src=url;await img.decode();this.images.set(url,img);}
 render(){const p=this.draft||this.s.record?.data.paper||defaults(),s=this.s;s.host.classList.toggle('cdt-paper-enabled',p.enabled);if(!p.enabled){s.host.style.background=this.original;return;}if(p.image&&!this.images?.has(p.image)){if(this.loading!==p.image){this.loading=p.image;this.loadImage(p.image).then(()=>s.scheduleRender()).catch(()=>new Notice('배경 용지 이미지를 읽지 못했습니다.'));}return;}const cr=s.canvas.canvasEl.getBoundingClientRect(),hr=s.host.getBoundingClientRect(),scale=cr.width/s.canvas.canvasEl.offsetWidth,url=this.texture(p);Object.assign(s.host.style,{backgroundColor:p.color,backgroundImage:url?`url("${url}")`:'none',backgroundRepeat:'repeat',backgroundSize:256*p.size/100*scale+'px',backgroundPosition:`${cr.left-hr.left}px ${cr.top-hr.top}px`});}
 open(){this.s.selection.end();this.s.finishStroke();const modal=new Modal(this.s.plugin.app);this.modal=modal;modal.modalEl.classList.add('cdt-dialog');const p={...defaults(),...this.s.record.data.paper};this.draft=p;modal.setTitle('Canvas 배경 용지');const el=(tag,parent,text)=>this.s.element(tag,'',parent,text),content=modal.contentEl;el('p',content,'이 Canvas의 배경에만 적용됩니다. 그림 레이어와 카드의 내용은 유지됩니다.');const row=(label)=>{const r=el('label',content);r.className='cdt-paper-row';el('span',r,label);return r;};const enabled=el('input',row('배경 용지 사용'));require('./ui-actions').bind(this.s,enabled.closest('label'),'action:paper-enabled','배경 용지 사용',()=>{});enabled.type='checkbox';enabled.checked=p.enabled;enabled.onchange=()=>{p.enabled=enabled.checked;this.s.scheduleRender();};const select=el('select',row('용지 프리셋'));for(const [value,text]of Object.entries(presets)){const option=el('option',select,text);option.value=value;}select.value=p.preset;select.onchange=()=>{p.preset=select.value;p.enabled=true;enabled.checked=true;if(p.preset==='kraft'){p.color='#c9b18a';color.value=p.color;}this.s.scheduleRender();};const color=el('input',row('바탕색'));color.type='color';color.value=p.color;color.oninput=()=>{p.color=color.value;this.s.scheduleRender();};for(const [key,label,min,max]of [['strength','재질 강도',0,100],['size','재질 크기 (%)',25,400]]){const r=row(label),range=el('input',r);range.type='range';range.min=min;range.max=max;range.value=p[key];range.setAttribute('aria-label',label);const num=el('input',r);num.type='number';num.min=min;num.max=max;num.value=p[key];num.setAttribute('aria-label',label+' 값');const change=value=>{p[key]=Math.max(min,Math.min(max,Number(value)||min));range.value=num.value=p[key];this.s.scheduleRender();};range.oninput=()=>change(range.value);num.onchange=()=>change(num.value);}
  const file=el('input',row('사용자 용지 이미지'));file.type='file';file.accept='image/png,image/jpeg,image/webp';file.setAttribute('aria-label','사용자 용지 이미지');file.onchange=async()=>{const f=file.files[0];if(!f)return;try{const url=await new Promise((resolve,reject)=>{const reader=new this.s.win.FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f);});await this.loadImage(url);if(this.modal!==modal)return;const img=this.images.get(url),c=this.s.doc.createElement('canvas');c.width=c.height=256;c.getContext('2d').drawImage(img,0,0,256,256);p.image=c.toDataURL();await this.loadImage(p.image);p.preset=select.value='custom';p.enabled=enabled.checked=true;this.s.scheduleRender();}catch(error){new Notice('용지 이미지를 열지 못했습니다. PNG/JPG/WebP를 선택해주세요.');}};el('p',content,'사용자 이미지는 반복되는 용지 재질로 적용됩니다. 강도와 크기를 조절할 수 있습니다.');const actions=el('div',content);actions.className='cdt-paper-actions';const cancel=el('button',actions,'취소');cancel.onclick=()=>modal.close();const apply=el('button',actions,'적용');apply.className='mod-cta';apply.onclick=()=>{const r=this.s.record;r.history.push(snapshot(r.data));r.data.paper={...p};r.data.version=Math.max(r.data.version,8);this.s.plugin.store.changed(r);this.s.plugin.queueSave();this.s.plugin.repaint(r);modal.close();};modal.onClose=()=>{this.draft=null;this.modal=null;this.s.scheduleRender();};modal.open();}
 destroy(){this.modal?.close();this.s.host.style.background=this.original;this.s.host.classList.remove('cdt-paper-enabled');}
}
module.exports={PaperUI,defaults};
