'use strict';
const ToolList=require('./tool-list');
const {Menu,setIcon}=require('obsidian');
const {shapePoints}=require('./figures');
const {shapeNames,keyFor,keyOf,shortcutDialog}=require('./tool-shortcuts');
class QuickTools{
 constructor(s){this.s=s;this.opened=false;s.plugin.settings.quickTools??=[];this.panel=s.element('aside','cdt-panel cdt-quick-tools',s.host);this.panel.hidden=true;this.button=s.button(s.tools,'star','지정 도구 모음',()=>this.toggle());this.button.oncontextmenu=e=>{e.preventDefault();const m=new Menu();m.addItem(i=>i.setTitle('단축키 설정').onClick(()=>shortcutDialog(s,'panel:quick','지정 도구 모음')));m.showAtMouseEvent(e);};}
 entries(){const q=this.s.plugin.settings;return [...q.presets.map(p=>({id:'preset:'+p.id,preset:p,name:(p.tool==='eraser'?'지우개 · ':'브러시 · ')+p.name,run:()=>this.s.brushUI.choose(p)})),...require('./shape-tools').ensure(q).map(t=>({id:'shape:'+t.id,kind:t.style.kind,name:'도형 · '+t.name,run:()=>require('./shape-tools').choose(this.s,t.id)})),...Object.entries({rectangle:'사각 선택',lasso:'올가미 선택','move-layer':'오브젝트'}).map(([tool,name])=>({id:'tool:'+tool,tool,name,run:()=>this.s.selectTool(tool)}))];}
 currentId(){const s=this.s,q=s.plugin.settings;return ['brush','eraser'].includes(s.tool)?'preset:'+(s.tool==='eraser'?q.selectedEraser:q.selectedBrush):s.tool==='shape'?'shape:'+(q.selectedShape||q.shapeStyle.kind):'tool:'+s.tool;}
 close(){this.opened=false;this.applyLayout();}
 toggle(){if(this.opened){this.close();this.s.workspaceUI?.applyLayout();return;}if(!this.s.drawing)this.s.setMode(true);this.opened=true;this.s.plugin.settings.contextCollapsed=false;const ids=this.s.plugin.settings.quickTools;if(!ids.includes(this.currentId())&&ids.length){const first=this.entries().find(e=>e.id===ids[0]);if(first)this.choose(first.id);}this.render();this.s.workspaceUI?.applyLayout();}
 choose(id){const entry=this.entries().find(e=>e.id===id);if(!entry)return;this.selecting=true;try{if(!this.s.drawing)this.s.setMode(true);entry.run();}finally{this.selecting=false;}this.render();this.s.workspaceUI?.applyLayout();}
 handleKey(e){const key=keyOf(e);if(!key)return false;const entry=this.entries().find(v=>keyFor(this.s.plugin.settings,v.id)===key);if(!entry)return false;e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)this.choose(entry.id);return true;}
 applyLayout(){const s=this.s,q=s.plugin.settings;this.panel.hidden=!this.opened||!s.drawing||q.contextCollapsed;this.panel.style.left=((q.toolbarWidth||42)+24)+'px';this.panel.style.width=(q.contextWidth||242)+'px';this.button.classList.toggle('is-active',this.opened);this.button.setAttribute('aria-pressed',String(this.opened));for(const [tool,b]of Object.entries({brush:s.brushButton,eraser:s.eraserButton,...s.editButtons})){const active=!this.opened&&(s.tool===tool||(tool==='rectangle'&&s.tool==='lasso'));b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',String(active));}if(!this.panel.hidden){s.panel.hidden=true;s.figures.panel.hidden=true;}}
 preview(parent,entry){const s=this.s;if(entry.preset)return s.brushUI.canvas(parent,entry.preset);const c=s.element('canvas','cdt-brush-preview',parent);c.width=220;c.height=64;const ctx=c.getContext('2d');ctx.strokeStyle='#eee9f5';ctx.lineWidth=2;ctx.lineJoin='round';if(entry.kind){const points=shapePoints(entry.kind,[20,18],[198,47]);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}else{ctx.setLineDash([5,4]);ctx.strokeRect(65,15,90,34);}return c;}
 render(){if(!this.opened||this.rendering)return;this.rendering=true;try{const s=this.s,p=this.panel;const scroll=p.querySelector('.cdt-preset-list')?.scrollTop||0;p.replaceChildren();s.brushUI.previews=s.brushUI.previews.filter(v=>v.c.isConnected);const head=s.element('div','cdt-color-head',p);s.element('strong','',head,'지정 도구');s.element('kbd','',head,s.plugin.settings.shortcuts.quick);s.button(head,'x','지정 도구 모음 닫기',()=>{this.close();s.workspaceUI.applyLayout();});const list=s.element('div','cdt-preset-list',p),all=this.entries(),current=this.currentId();for(const id of s.plugin.settings.quickTools){const entry=all.find(e=>e.id===id);if(!entry)continue;const button=s.element('button','cdt-preset'+(id===current?' is-active':''),list);button.setAttribute('aria-label',entry.name);button.setAttribute('aria-pressed',String(id===current));ToolList.draggable(s,button,id,()=>[...s.plugin.settings.quickTools],ids=>{s.plugin.settings.quickTools=ids;s.plugin.saveData(s.plugin.settings);},()=>this.render());this.preview(button,entry);s.element('span','cdt-preset-name',button,entry.name);const key=keyFor(s.plugin.settings,id);if(key)s.element('kbd','cdt-tool-key',button,key);button.onclick=()=>this.choose(id);button.oncontextmenu=e=>{e.preventDefault();this.context(id,e);};}list.scrollTop=scroll;s.element('p','cdt-hint',p,'각 도구 패널에서 우클릭하여 등록');const entry=all.find(e=>e.id===current&&s.plugin.settings.quickTools.includes(e.id));if(entry){require('./panel-layout').split(s,p,list,'quick');const properties=s.element('div','cdt-quick-properties',p);if(entry.preset)s.brushUI.properties(properties);else{ s.element('div','cdt-section-label',properties,'도구 속성');this.preview(properties,entry);if(entry.kind)s.figures.properties(properties);else s.element('p','cdt-hint',properties,'Canvas에서 드래그하여 조작합니다.');}}else s.element('p','cdt-hint',p,list.children.length?'위 목록에서 사용할 도구를 선택하세요.':'등록한 도구가 없습니다.');this.applyLayout();const active=list.querySelector('.is-active');if(active&&!p.hidden){const a=active.getBoundingClientRect(),r=list.getBoundingClientRect();if(a.top<r.top)list.scrollTop-=r.top-a.top;else if(a.bottom>r.bottom)list.scrollTop+=a.bottom-r.bottom;}}finally{this.rendering=false;}}
 addMenu(menu,id){const s=this.s,registered=s.plugin.settings.quickTools.includes(id);menu.addItem(i=>i.setTitle(registered?'지정 도구에서 제거':'지정 도구로 등록').onClick(()=>{const q=s.plugin.settings;q.quickTools=registered?q.quickTools.filter(v=>v!==id):[...new Set([...q.quickTools,id])];s.plugin.saveData(q);for(const session of s.plugin.sessions.values()){if(['brush','eraser'].includes(session.tool))session.brushUI?.render();session.figures?.panelRender();session.quickTools?.render();}}));}
 context(id,e){const menu=new Menu();this.addMenu(menu,id);if(id.startsWith('shape:')){menu.addItem(i=>i.setTitle('복제').onClick(()=>require('./shape-tools').duplicate(this.s,id.slice(6))));menu.addItem(i=>i.setTitle('이름 변경').onClick(()=>{const t=require('./shape-tools').ensure(this.s.plugin.settings).find(t=>t.id===id.slice(6));this.s.brushUI.nameDialog('도형 도구 이름',t.name,name=>{t.name=name;this.s.plugin.saveData(this.s.plugin.settings);this.s.figures.panelRender();this.render()})}));}const name=this.entries().find(v=>v.id===id)?.name||'도구';menu.addItem(i=>i.setTitle('단축키 설정').onClick(()=>shortcutDialog(this.s,id,name)));menu.showAtMouseEvent(e);}
 destroy(){this.panel.remove();this.button.remove();}
}
module.exports={QuickTools};
