'use strict';
const {Notice}=require('obsidian');
const {makeLayer,descendants,ancestors,writable,snapshot,restore}=require('./layers');
const R=require('./raster-edit');
const clone=x=>JSON.parse(JSON.stringify(x));
class DrawingSelection{
 constructor(s){this.s=s;this.make=()=>s.doc.createElement('canvas');this.matrix=R.identity();this.parts=[];this.svg=s.doc.createElementNS('http://www.w3.org/2000/svg','svg');this.svg.classList.add('cdt-selection');s.host.append(this.svg);this.bar=s.element('div','cdt-selection-bar',s.host);this.bar.hidden=true;
  for(const [icon,label,fn]of [['check','변형 확정 (Enter)',()=>this.confirm(false)],['x','선택 / 변형 취소 (Esc)',()=>this.cancel()],['flip-horizontal-2','좌우 반전',()=>this.flip(-1,1)],['flip-vertical-2','상하 반전',()=>this.flip(1,-1)],['rotate-cw','90도 회전',()=>this.rotate()],['copy','그림 복사 (Ctrl+C)',()=>this.copy()],['scissors','그림 잘라내기 (Ctrl+X)',()=>this.cut()],['clipboard-paste','그림 붙여넣기 (Ctrl+V)',()=>this.paste()],['layers-2','선택 영역을 새 레이어로 분리',()=>this.separate()],['trash-2','선택 영역 삭제',()=>this.remove()]])s.button(this.bar,icon,label,()=>this.safe(fn));
  this.caption=s.element('span','cdt-selection-caption',this.bar);
 }
 prepareRegions(regions){this.regions=clone(regions);this.s.engine.overrides=null;this.parts=this.targets().map(l=>({id:l.id,...R.split(this.make,this.s.engine.leaf(this.d,l),this.regions)}));this.box=R.bounds(this.regions.filter(r=>r.op!=='subtract').flatMap(r=>r.points));this.polygon=null;this.matrix=R.identity();this.dirty=false;this.revision=this.d.revision;this.s.scheduleRender();return !!this.box;}
 get d(){return this.s.record.data;}
 safe(fn){const fail=error=>{new Notice('그림 편집을 적용하지 못했습니다: '+error.message);this.cancel();};try{const value=fn();if(value?.catch)value.catch(fail);return value;}catch(error){fail(error);}}
 targets(){const ids=new Set(this.d.selectedLayers.flatMap(id=>[...descendants(this.d,id)]));return this.d.layers.filter(l=>ids.has(l.id)&&writable(this.d,l));}
 prepare(polygon){if(polygon?.[0]?.points)return this.prepareRegions(polygon);if(polygon)return this.prepareRegions([{op:'add',points:polygon}]);this.regions=null;this.s.finishStroke();this.parts=this.targets().map(l=>({id:l.id,...R.split(this.make,this.s.engine.leaf(this.d,l),polygon)})).filter(p=>R.inkBounds(p.selected));this.polygon=polygon||R.corners(R.bounds(this.parts.flatMap(p=>R.corners(R.inkBounds(p.selected))))||{left:0,top:0,right:0,bottom:0});this.box=R.bounds(this.polygon);this.matrix=R.identity();this.dirty=false;this.revision=this.d.revision;this.s.scheduleRender();if(!this.parts.length){this.clear();new Notice('선택한 레이어의 편집 가능한 그림이 없습니다. 잠금·숨김 상태를 확인해주세요.');return false;}return true;}
 clear(){this.regions=null;this.matrix=R.identity();this.parts=[];this.polygon=null;this.box=null;this.dirty=false;this.drag=null;this.s.engine.overrides=null;this.s.scheduleRender();}
 cancel(){if(this.pasting){this.endPaste();return;}this.release();this.clear();}
 release(){if(this.drag&&this.s.host.hasPointerCapture(this.drag.id))this.s.host.releasePointerCapture(this.drag.id);this.drag=null;}
 end(){this.endPaste();this.cancel();}
 valid(){if(this.d.revision!==this.revision||this.parts.some(p=>!writable(this.d,this.d.layers.find(l=>l.id===p.id)))){this.cancel();new Notice('레이어가 변경되어 편집 미리보기를 취소했습니다. 다시 선택해주세요.');return false;}return true;}
 preview(){if(!this.parts.length||!this.valid())return;this.s.engine.overrides=new Map(this.parts.map(p=>[p.id,R.merge(this.make,p.remainder,R.transform(this.make,p.selected,this.matrix))]));this.dirty=true;this.s.scheduleRender();}
 commit(fn,before=snapshot(this.d)){try{fn();require('./history-state').seal(this.d);}catch(error){restore(this.d,before);throw error;}const r=this.s.record;r.data.version=Math.max(r.data.version,8);r.history.push(before);this.s.plugin.store.changed(r);this.s.plugin.queueSave();this.s.plugin.repaint(r);this.s.plugin.refreshLayers(r);}
 write(id,tiles){const l=this.d.layers.find(l=>l.id===id);l.tiles=R.serialize(tiles,this.s.engine);l.offset={x:0,y:0};this.d.strokes=this.d.strokes.filter(s=>s.layerId!==id);}
 confirm(keep=true){if(!this.parts.length||!this.valid())return;if(!this.dirty){if(!keep)this.clear();return;}const polygon=this.regions?this.regions.map(r=>({op:r.op,points:r.points.map(p=>R.point(this.matrix,p))})):this.polygon.map(p=>R.point(this.matrix,p)),outputs=this.parts.map(p=>[p.id,R.merge(this.make,p.remainder,R.transform(this.make,p.selected,this.matrix))]);this.commit(()=>outputs.forEach(([id,map])=>this.write(id,map)));this.s.engine.overrides=null;if(keep)this.prepare(polygon);else this.clear();}
 flip(x,y){if(!this.box)return;const b=this.box;this.matrix=R.multiply(this.matrix,R.around([(b.left+b.right)/2,(b.top+b.bottom)/2],[x,0,0,y,0,0]));this.preview();}
 rotate(){if(!this.box)return;const b=this.box;this.matrix=R.multiply(this.matrix,R.around([(b.left+b.right)/2,(b.top+b.bottom)/2],[0,1,-1,0,0,0]));this.preview();}
 remove(){if(!this.parts.length||!this.valid())return;this.commit(()=>this.parts.forEach(p=>this.write(p.id,p.remainder)));this.clear();}
 separate(){if(!this.parts.length||!this.valid())return;const source=this.parts.map(p=>({l:this.d.layers.find(l=>l.id===p.id),map:R.transform(this.make,p.selected,this.matrix)}));this.commit(()=>{const group=source.length>1?makeLayer('분리한 그림','group'):null;if(group)this.d.layers.unshift(group);const created=source.map(({l,map})=>({...clone(l),id:makeLayer().id,name:l.name+' 분리',parent:group?.id||l.parent,tiles:R.serialize(map,this.s.engine),offset:{x:0,y:0},clip:false,locked:false}));this.parts.forEach(p=>this.write(p.id,p.remainder));if(group)this.d.layers.splice(1,0,...created);else this.d.layers.splice(this.d.layers.indexOf(source[0].l),0,...created);this.d.selectedLayers=[group?.id||created[0].id];});this.clear();}
 copy(){if(this.dirty){new Notice('변형을 확정한 뒤 복사해주세요.');return false;}if(!this.parts.length){if(!this.prepare(null))return false;this.s.tool='rectangle';this.s.refreshControls();}if(!this.valid())return false;this.s.plugin.drawingClipboardImage=require('./image-paste').signature();this.s.plugin.drawingClipboard={box:clone(this.box),groups:clone(this.d.layers.filter(l=>l.type==='group'&&this.parts.some(p=>ancestors(this.d,this.d.layers.find(n=>n.id===p.id)).some(a=>a.id===l.id)))),parts:this.parts.map(p=>({layer:clone(this.d.layers.find(l=>l.id===p.id)),tiles:R.serialize(p.selected,this.s.engine)}))};new Notice('선택한 그림을 복사했습니다.');return true;}
 cut(){if(this.copy())this.remove();}
 async paste(){const clip=this.s.plugin.drawingClipboard;if(!clip){new Notice('복사한 Drawing 그림이 없습니다.');return;}this.end();this.pasting={clip:clone(clip),before:null,count:0,at:null};await this.s.engine.load({layers:clip.parts.map(p=>({tiles:p.tiles}))});if(!this.pasting)return;this.s.tool='rectangle';this.s.refreshControls();this.positionPaste(this.s.lastPointer?this.s.point(this.s.lastPointer):[this.s.canvas.x,this.s.canvas.y]);new Notice('왼쪽 클릭으로 반복 배치 · 오른쪽 클릭 또는 Esc로 끝내기');}
 pasteLayers(at,ghost=false){const paste=this.pasting,b=paste.clip.box,dx=Math.round(at[0]-(b.left+b.right)/2),dy=Math.round(at[1]-(b.top+b.bottom)/2),group=paste.clip.parts.length>1?makeLayer('붙여넣은 그림','group'):null,created=[];const groups=group?(paste.clip.groups||[]):[],ids=new Map(groups.map(g=>[g.id,makeLayer().id]));if(group){if(ghost)group.opacity=.5;created.push(group);for(const g of groups)created.push({...clone(g),id:ids.get(g.id),parent:ids.get(g.parent)||group.id,locked:false,anchor:null,tiles:[]});}for(const part of paste.clip.parts){const raw=new Map(part.tiles.map(t=>[t.x+','+t.y,{x:t.x,y:t.y,c:this.s.engine.images.get(t.png)}]));const l={...clone(part.layer),id:makeLayer().id,parent:ids.get(part.layer.parent)||group?.id||null,clip:group?part.layer.clip:false,name:part.layer.name+' 붙여넣기',locked:false,alphaLock:false,anchor:null,offset:{x:0,y:0},tiles:R.serialize(R.transform(this.make,raw,R.translation(dx,dy)),this.s.engine)};if(ghost&&!group)l.opacity*=.5;created.push(l);}return created;}
 positionPaste(at){if(!this.pasting)return;this.pasting.at=at;const ghost=this.pasteLayers(at,true);this.previewData={...this.d,layers:[...ghost,...this.d.layers]};this.s.scheduleRender();}
 place(){if(!this.pasting?.at)return;const layers=this.pasteLayers(this.pasting.at);if(!this.pasting.before)this.pasting.before=snapshot(this.d);this.d.layers.unshift(...layers);this.d.selectedLayers=[layers[0].id];this.d.version=Math.max(this.d.version,8);this.s.plugin.store.changed(this.s.record);this.s.plugin.queueSave();this.s.plugin.refreshLayers(this.s.record);this.pasting.count++;this.positionPaste(this.pasting.at);}
 endPaste(){if(!this.pasting)return;if(this.pasting.before){this.s.record.history.push(this.pasting.before);this.s.plugin.queueSave();}this.pasting=null;this.previewData=null;this.s.scheduleRender();}
 hit(p){if(this.regions)return require('./selection-mask').contains(this.regions,R.point(R.inverse(this.matrix),p));if(!this.box)return false;const q=R.point(R.inverse(this.matrix),p),b=this.box;return q[0]>=b.left&&q[0]<=b.right&&q[1]>=b.top&&q[1]<=b.bottom;}
 down(e){if(this.pasting){e.preventDefault();e.stopImmediatePropagation();if(e.button===2){this.suppressContextUntil=Date.now()+700;this.endPaste();}else if(e.button===0){this.positionPaste(this.s.point(e));this.place();}return true;}if(!['rectangle','lasso','move-layer'].includes(this.s.tool))return false;if(e.button!==0)return true;e.preventDefault();e.stopImmediatePropagation();this.s.doc.activeElement?.blur();const p=this.s.point(e),handle=e.target.dataset?.handle;
  if(this.s.tool!=='move-layer'&&(e.shiftKey||e.altKey)){if(this.dirty)this.confirm(true);const prior=clone(this.regions||[]);this.polygon=[p];this.drag={kind:'select',polygon:[p],prior,op:e.altKey?'subtract':'add'};}
  else if(this.s.tool==='move-layer'){if(!this.parts.length&&!this.prepare(null))return true;if(!this.valid())return true;this.drag={kind:handle==='rotate'?'rotate':handle?'scale':'move',handle,full:!!this.s.ctrlObject};}
  else if(handle||this.hit(p)){this.drag={kind:handle==='rotate'?'rotate':handle?'scale':'move',handle};}
  else{this.clear();this.polygon=[p];this.drag={kind:'select',polygon:[p],prior:[],op:'add'};}
  Object.assign(this.drag,{id:e.pointerId,start:p,matrix:this.matrix.slice()});this.s.host.setPointerCapture(e.pointerId);return true;
 }
 move(e){if(this.pasting){if(this.s.host.contains(e.target)&&!e.target.closest('.cdt-toolbar,.cdt-panel,.cdt-layers,.cdt-selection-bar'))this.positionPaste(this.s.point(e));return true;}const drag=this.drag;if(!drag||drag.id!==e.pointerId)return false;e.preventDefault();e.stopImmediatePropagation();const p=this.s.point(e),b=this.box;
  if(drag.kind==='select'){if(this.s.tool==='lasso'){const last=drag.polygon.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])>1)drag.polygon.push(p);this.polygon=drag.polygon;}else this.polygon=R.corners(R.bounds([drag.start,p]));this.s.scheduleRender();return true;}
  if(drag.kind==='move')this.matrix=R.multiply(R.translation(Math.round(p[0]-drag.start[0]),Math.round(p[1]-drag.start[1])),drag.matrix);
  else if(drag.kind==='rotate'){const center=R.point(drag.matrix,[(b.left+b.right)/2,(b.top+b.bottom)/2]);let angle=Math.atan2(p[1]-center[1],p[0]-center[0])-Math.atan2(drag.start[1]-center[1],drag.start[0]-center[0]);if(e.shiftKey)angle=Math.round(angle/(Math.PI/12))*Math.PI/12;this.matrix=R.multiply(R.around(center,[Math.cos(angle),Math.sin(angle),-Math.sin(angle),Math.cos(angle),0,0]),drag.matrix);}
  else{const h=drag.handle,anchor=[h.includes('w')?b.right:h.includes('e')?b.left:(b.left+b.right)/2,h.includes('n')?b.bottom:h.includes('s')?b.top:(b.top+b.bottom)/2],start=R.point(R.inverse(drag.matrix),drag.start),now=R.point(R.inverse(drag.matrix),p);let sx=/w|e/.test(h)?(now[0]-anchor[0])/(start[0]-anchor[0]):1,sy=/n|s/.test(h)?(now[1]-anchor[1])/(start[1]-anchor[1]):1;if(e.shiftKey&&h.length===2)sx=sy=Math.abs(sx)>Math.abs(sy)?sx:sy;const clamp=v=>Math.abs(v)<.02?(v<0?-.02:.02):v;this.matrix=R.multiply(drag.matrix,R.around(anchor,[clamp(sx),0,0,clamp(sy),0,0]));}
  this.preview();return true;
 }
 up(e){if(!this.drag||this.drag.id!==e.pointerId)return false;const drag=this.drag;e.preventDefault();e.stopImmediatePropagation();this.release();if(e.type==='pointercancel'){this.cancel();return true;}if(drag.kind==='select'){const b=R.bounds(this.polygon);if(this.polygon.length<3||b.right-b.left<2||b.bottom-b.top<2)this.clear();else this.prepareRegions([...(drag.prior||[]),{op:drag.op||'add',points:this.polygon}]);}else if(drag.full)this.confirm(false);return true;}
 key(e){if(!this.s.drawing)return false;const ctrl=e.ctrlKey||e.metaKey;let action;if(e.code==='Escape')action=()=>this.cancel();else if(e.code==='Enter'&&this.parts.length)action=()=>this.confirm(false);else if((e.code==='Delete'||e.code==='Backspace')&&this.parts.length)action=()=>this.remove();else if(ctrl&&e.code==='KeyC')action=()=>this.copy();else if(ctrl&&e.code==='KeyX')action=()=>this.cut();else if(ctrl&&e.code==='KeyV'){if(require('./image-paste').nativeImage(this.s))action=()=>require('./image-paste').paste(this.s);else action=()=>this.paste();}if(!action)return false;e.preventDefault();e.stopImmediatePropagation();this.safe(action);return true;}
 render(){this.svg.replaceChildren();this.bar.hidden=!this.s.drawing||(!this.parts.length&&!this.pasting);if(!this.s.drawing)return;const cr=this.s.canvas.canvasEl.getBoundingClientRect(),hr=this.s.host.getBoundingClientRect(),scale=cr.width/this.s.canvas.canvasEl.offsetWidth,screen=p=>[p[0]*scale+cr.left-hr.left,p[1]*scale+cr.top-hr.top];const node=(tag,attrs)=>{const n=this.s.doc.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);this.svg.append(n);return n;};if(this.regions?.length&&this.box){const b=this.box,sb=R.bounds(R.corners(b).map(p=>screen(R.point(this.matrix,p)))),lo=[sb.left,sb.top],hi=[sb.right,sb.bottom];const defs=node('defs',{}),mask=this.s.doc.createElementNS(this.svg.namespaceURI,'mask');mask.id='cdt-region-'+this.d.id;mask.setAttribute('maskUnits','userSpaceOnUse');mask.setAttribute('x','-100000');mask.setAttribute('y','-100000');mask.setAttribute('width','200000');mask.setAttribute('height','200000');defs.append(mask);for(const r of this.regions){const poly=this.s.doc.createElementNS(this.svg.namespaceURI,'polygon');poly.setAttribute('points',r.points.map(p=>screen(R.point(this.matrix,p))).map(p=>p.join(',')).join(' '));poly.setAttribute('fill',r.op==='subtract'?'black':'white');mask.append(poly);}node('rect',{x:Math.min(lo[0],hi[0]),y:Math.min(lo[1],hi[1]),width:Math.abs(hi[0]-lo[0]),height:Math.abs(hi[1]-lo[1]),fill:'#9770ff','fill-opacity':'.13',mask:'url(#'+mask.id+')',class:'cdt-region-fill'});}let poly=this.polygon;if(poly){poly=poly.map(p=>screen(R.point(this.matrix,p)));node('polygon',{points:poly.map(p=>p.join(',')).join(' '),class:'cdt-selection-outline'});}
  if(this.box&&this.parts.length&&['rectangle','lasso','move-layer'].includes(this.s.tool)){const b=this.box;const handles={nw:[b.left,b.top],n:[(b.left+b.right)/2,b.top],ne:[b.right,b.top],e:[b.right,(b.top+b.bottom)/2],se:[b.right,b.bottom],s:[(b.left+b.right)/2,b.bottom],sw:[b.left,b.bottom],w:[b.left,(b.top+b.bottom)/2]};const box=R.corners(b).map(p=>screen(R.point(this.matrix,p)));node('polygon',{points:box.map(p=>p.join(',')).join(' '),class:'cdt-transform-box'});for(const [key,p]of Object.entries(handles)){const [x,y]=screen(R.point(this.matrix,p));node('rect',{x:x-4,y:y-4,width:8,height:8,'data-handle':key,class:'cdt-transform-handle'});}const n=screen(R.point(this.matrix,handles.n)),center=screen(R.point(this.matrix,[(b.left+b.right)/2,(b.top+b.bottom)/2])),len=Math.hypot(n[0]-center[0],n[1]-center[1])||1,rot=[n[0]+28*(n[0]-center[0])/len,n[1]+28*(n[1]-center[1])/len];node('line',{x1:n[0],y1:n[1],x2:rot[0],y2:rot[1],class:'cdt-transform-box'});node('circle',{cx:rot[0],cy:rot[1],r:5,'data-handle':'rotate',class:'cdt-transform-handle'});const sb=R.bounds(box);const right=this.s.layers.hidden?hr.width-12:this.s.layers.getBoundingClientRect().left-hr.left-12;this.bar.style.left=Math.max(65,Math.min(right-400,sb.left))+'px';this.bar.style.top=Math.max(8,Math.min(hr.height-80,sb.bottom+14))+'px';}
  if(this.pasting){this.bar.style.left='35%';this.bar.style.top=(hr.height-65)+'px';}if(this.regions&&!['rectangle','lasso','move-layer'].includes(this.s.tool))this.bar.hidden=true;this.caption.textContent=this.pasting?'왼쪽 클릭: 배치 · 오른쪽 클릭: 끝내기':this.dirty?'Enter: 확정 · Esc: 취소':'Shift: 선택 추가 · Alt: 선택 제외 · Esc: 해제';for(const b of this.bar.querySelectorAll('button'))b.hidden=!!this.pasting&&!b.title.includes('취소');
 }
 destroy(){this.end();this.svg.remove();this.bar.remove();}
}
module.exports={DrawingSelection};
