'use strict';
const {setIcon}=require('obsidian');
const {fontControl}=require('./font-list');
const {presets}=require('./figures');
const defaults=()=>({color:'#333333',size:24,fontFamily:'',background:false,bgColor:'#ffffff',bgOpacity:100,border:false,borderColor:'#808080',borderWidth:1,borderOpacity:100,radius:0,padding:8});
const clone=x=>JSON.parse(JSON.stringify(x));
const rgba=(hex,a)=>/^#[0-9a-f]{6}$/i.test(hex)?`rgba(${parseInt(hex.slice(1,3),16)},${parseInt(hex.slice(3,5),16)},${parseInt(hex.slice(5,7),16)},${a/100})`:'transparent';
class TextItems{
 constructor(s){this.s=s;this.nodes=new Map();this.drafts=new Set();this.resizeBases=new Map();s.listen(s.host,'pointerdown',e=>{this.resizeBases.clear();if(e.button!==0)return;for(const n of s.canvas.nodes.values()){if(!this.isText(n))continue;const r=n.nodeEl.getBoundingClientRect();if(e.clientX>=r.left-8&&e.clientX<=r.right+8&&e.clientY>=r.top-8&&e.clientY<=r.bottom+8&&(Math.abs(e.clientX-r.left)<9||Math.abs(e.clientX-r.right)<9||Math.abs(e.clientY-r.top)<9||Math.abs(e.clientY-r.bottom)<9))this.resizeBases.set(n,{width:n.width,height:n.height,size:n.unknownData.cdtText.size});}},true);s.listen(s.win,'pointerup',()=>s.win.setTimeout(()=>{const resized=this.resizeBases.size;this.resizeBases.clear();if(resized&&s.tool==='text')s.figures.panelRender();},0),true);s.listen(s.win,'pointercancel',()=>this.resizeBases.clear(),true);s.plugin.settings.textStyle??=defaults();s.listen(s.doc,'keydown',e=>{if(e.code==='Escape'&&s.isActive()&&!e.target.closest('.modal')&&!s.figures.panel.hidden&&(s.tool==='text'||this.current)){this.closePanel();}},true);s.listen(s.host,'click',e=>{if(!this.armed&&!this.at(e)&&!e.target.closest('.cdt-history,.cdt-panel-edge,.cdt-panel,.cdt-layers,.cdt-toolbar,.canvas-node,.canvas-card-menu,.canvas-menu,.canvas-controls'))this.closePanel();if(s.drawing&&s.tool!=='text')return;const n=this.at(e);if(n&&!n.isEditing&&!e.ctrlKey&&!e.metaKey){e.preventDefault();e.stopImmediatePropagation();if(e.shiftKey)s.canvas.toggleSelect(n);else s.canvas.selectOnly(n);}},true);s.listen(s.host,'dblclick',e=>{if(s.drawing&&s.tool!=='text')return;const n=this.at(e);if(n){e.preventDefault();e.stopImmediatePropagation();s.canvas.selectOnly(n);n.startEditing();this.panelClosed=false;this.selected=n;s.tool='text';s.figures.panelRender();}},true);this.timer=s.win.setInterval(()=>this.sync(),160);}
 isText(n){return !!n?.unknownData?.cdtText;}
 at(e){if(e.target.closest('.cdt-history,.cdt-panel-edge,.cdt-panel,.cdt-layers,.cdt-toolbar,.canvas-controls,.canvas-menu,.canvas-card-menu'))return null;return [...this.s.canvas.nodes.values()].filter(n=>this.isText(n)).sort((a,b)=>b.zIndex-a.zIndex).find(n=>{const r=n.nodeEl.getBoundingClientRect();return n.nodeEl.contains(e.target)||(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom);});}
 get current(){const selected=[...this.s.canvas.selection].find(n=>this.isText(n));return selected||null;}
 sync(){if(!this.s.ready||this.s.disposed)return;this.installCreateButton();this.pruneDrafts();for(const n of this.s.canvas.nodes.values()){if(!this.isText(n))continue;if(!this.nodes.has(n)){const original=n.moveAndResize,originalGet=n.getData,owner=this;const getData=function(){const d=originalGet.call(this);if(d.cdtText)d.cdtText=clone(d.cdtText);return d;};n.getData=getData;const wrapped=function(rect){const resize=owner.resizeBases.has(this)&&(rect.width!==undefined&&rect.width!==this.width||rect.height!==undefined&&rect.height!==this.height);const result=original.call(this,rect);if(resize){this.unknownData.cdtText.autoFit=true;owner.fitKeys?.delete(this);owner.fit(this);}return result;};n.moveAndResize=wrapped;this.nodes.set(n,()=>{if(n.getData===getData)n.getData=originalGet;if(n.moveAndResize===wrapped)n.moveAndResize=original;n.nodeEl.classList.remove('cdt-text-item');});}this.decorate(n);this.fit(n);}for(const[n,off]of this.nodes)if(!this.s.canvas.nodes.has(n.id)||this.s.canvas.nodes.get(n.id)!==n){off();this.nodes.delete(n);}if(this.current!==this.selected){this.selected=this.current;if(this.s.tool==='text')this.s.figures.panelRender();}}
 decorate(n){const st={...defaults(),...n.unknownData.cdtText};n.nodeEl.classList.add('cdt-text-item');const css=n.nodeEl.style;for(const[k,v]of Object.entries({'--cdt-text-font':st.fontFamily?JSON.stringify(st.fontFamily):'var(--font-text)', '--cdt-text-color':st.color,'--cdt-text-size':st.size+'px','--cdt-text-bg':st.background?rgba(st.bgColor,st.bgOpacity):'transparent','--cdt-text-border':rgba(st.borderColor,st.borderOpacity),'--cdt-text-border-width':(st.border?Math.max(1,st.borderWidth):0)+'px','--cdt-text-radius':st.radius+'px','--cdt-text-padding':st.padding+'px'}))if(css.getPropertyValue(k)!==v)css.setProperty(k,v);const frame=n.nodeEl.querySelector('iframe')?.contentDocument;if(frame?.head){this.editorFrames??=new WeakSet();if(!this.editorFrames.has(frame)){this.editorFrames.add(frame);this.s.listen(frame,'keydown',e=>{if(e.code==='Escape')this.closePanel();},true);}let style=frame.querySelector('style[data-cdt-text]');if(!style){style=frame.createElement('style');style.dataset.cdtText='true';frame.head.append(style);}const text=`html,body,.view-content,.markdown-source-view,.cm-editor,.cm-scroller{background:transparent!important}html,body{margin:0!important}.markdown-source-view{--font-text-size:${st.size}px;--text-normal:${st.color};--h1-color:${st.color};--h2-color:${st.color};--h3-color:${st.color};--bold-color:${st.color};font-family:${st.fontFamily?JSON.stringify(st.fontFamily):'var(--font-text)'}!important;--font-text:${st.fontFamily?JSON.stringify(st.fontFamily):'var(--font-interface)'};font-size:${st.size}px!important;background:transparent!important}.cm-content{padding:0!important;min-height:0!important}.cm-line{font-family:inherit}.cm-scroller{padding:0!important;overflow:auto!important}.cm-editor{height:auto!important;min-height:0!important}.cm-sizer{min-height:0!important;padding:0!important}.markdown-source-view{padding:0!important}`;if(style.textContent!==text)style.textContent=text;}}
 pruneDrafts(){for(const n of this.drafts){if(n.isEditing)continue;this.drafts.delete(n);if(this.s.canvas.nodes.get(n.id)===n&&!String(n.getData().text||'').trim()){this.s.canvas.removeNode(n);this.s.canvas.requestSave();}}}
 closePanel(){this.panelClosed=true;if(this.s.tool==='text')this.s.figures.panel.hidden=true;}
 fit(n){const st=n.unknownData.cdtText;if(!st.autoFit||n.isEditing)return;const preview=n.nodeEl.querySelector('.markdown-preview-view');if(!preview?.textContent?.trim()||!preview.clientWidth||!preview.clientHeight)return;preview.style.setProperty('overflow','hidden','important');const section=preview.querySelector('.markdown-preview-sizer');if(section)for(const[k,v]of Object.entries({height:'auto',minHeight:'0',maxHeight:'none',margin:'0',padding:'0'}))section.style[k]=v;this.fitKeys??=new WeakMap();const key=[n.width,n.height,preview.clientWidth,preview.clientHeight,preview.innerHTML,st.fontFamily,st.padding,st.border,st.borderWidth].join('|');if(this.fitKeys.get(n)===key&&preview.scrollHeight<=preview.clientHeight&&preview.scrollWidth<=preview.clientWidth)return;this.fitKeys.set(n,key);let low=.25,high=600;for(let i=0;i<13;i++){const size=(low+high)/2;n.nodeEl.style.setProperty('--cdt-text-size',size+'px');if(preview.scrollHeight<=preview.clientHeight&&preview.scrollWidth<=preview.clientWidth)low=size;else high=size;}st.size=Math.floor(low*98)/100;this.decorate(n);preview.scrollTop=0;preview.scrollLeft=0;this.s.canvas.requestSave();}


 panelRender(panel){const s=this.s,n=this.current;let st={...defaults(),...(n?n.unknownData.cdtText:s.plugin.settings.textStyle)};const heading=s.element('div','cdt-color-head',panel);s.element('strong','',heading,'텍스트');s.button(heading,'x','텍스트 속성 닫기',()=>{this.panelClosed=true;panel.hidden=true;});s.element('p','cdt-hint',panel,n?'선택한 텍스트의 스타일':'T 선택 → Canvas에서 드래그 → 입력\n더블클릭: Markdown 편집');const change=(key,v)=>{st={...defaults(),...(n?n.unknownData.cdtText:s.plugin.settings.textStyle),[key]:v};if(key==='size')st.autoFit=false;if(n)n.unknownData.cdtText=clone(st);s.plugin.settings.textStyle=clone(st);s.plugin.saveData(s.plugin.settings);if(n){this.decorate(n);this.fit(n);s.canvas.requestSave();}};const color=(label,key)=>{const row=s.element('label','cdt-text-field',panel);s.element('span','',row,label);const input=s.element('input','',row);input.type='color';input.value=st[key];input.setAttribute('aria-label',label);input.oninput=()=>change(key,input.value);};const num=(label,key,min,max)=>s.figures.field(panel,label,st[key],min,max,v=>change(key,v));const check=(label,key)=>{const row=s.element('label','cdt-text-field',panel),i=s.element('input','',row);i.type='checkbox';i.checked=st[key];i.setAttribute('aria-label',label);s.element('span','',row,label);i.onchange=()=>change(key,i.checked);require('./ui-actions').bind(s,row,'action:text:'+key,label,()=>{});};fontControl(s,panel,st.fontFamily,v=>change('fontFamily',v));color('글자 색','color');num('글자 크기','size',8,600);check('배경색 사용','background');color('배경색','bgColor');num('배경 불투명도','bgOpacity',0,100);check('테두리 사용','border');color('테두리 색','borderColor');num('테두리 두께','borderWidth',1,12);num('테두리 불투명도','borderOpacity',0,100);presets(s,panel,'text',()=>st,value=>{const style={...defaults(),...value};s.plugin.settings.textStyle=clone(style);s.plugin.saveData(s.plugin.settings);if(n){n.unknownData.cdtText=clone(style);this.decorate(n);this.fit(n);s.canvas.requestSave();}s.figures.panelRender();});}
 installCreateButton(){const s=this.s,menu=s.host.querySelector('.canvas-card-menu');if(!menu||menu.querySelector('.cdt-create-text'))return;const b=this.createButton=s.element('div','canvas-card-menu-button cdt-create-text',menu);setIcon(b,'type');b.setAttribute('role','button');b.tabIndex=0;b.title='텍스트 만들기 · 클릭 후 Canvas에서 드래그';b.setAttribute('aria-label','텍스트 만들기');const activate=e=>{e.preventDefault();e.stopPropagation();if(s.drawing)return;this.panelClosed=false;s.selectTool('text');this.armed=true;b.setAttribute('aria-pressed','true');};b.onclick=activate;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')activate(e);};}

 down(e){const s=this.s;if(s.tool!=='text'||!this.armed)return false;const n=this.at(e);if(n)return true;if(e.button!==0)return true;e.preventDefault();e.stopImmediatePropagation();const wasEditing=[...s.canvas.nodes.values()].some(n=>this.isText(n)&&n.isEditing);s.doc.activeElement?.blur();for(const n of s.canvas.nodes.values())if(n.isEditing)n.blur();s.canvas.deselectAll();if(wasEditing)return true;this.drag={id:e.pointerId,start:s.point(e)};this.ghost=s.element('div','cdt-text-ghost',s.host);s.host.setPointerCapture(e.pointerId);return true;}
 move(e){if(this.drag?.id!==e.pointerId)return false;e.preventDefault();e.stopImmediatePropagation();this.drag.end=this.s.point(e);const s=this.s,cr=s.canvas.canvasEl.getBoundingClientRect(),hr=s.host.getBoundingClientRect(),scale=cr.width/s.canvas.canvasEl.offsetWidth,a=this.drag.start,b=this.drag.end;Object.assign(this.ghost.style,{left:(Math.min(a[0],b[0])*scale+cr.left-hr.left)+'px',top:(Math.min(a[1],b[1])*scale+cr.top-hr.top)+'px',width:Math.max(80,Math.abs(b[0]-a[0]))*scale+'px',height:Math.max(45,Math.abs(b[1]-a[1])*scale)+'px'});return true;}
 up(e){if(this.drag?.id!==e.pointerId)return false;e.preventDefault();e.stopImmediatePropagation();const s=this.s,a=this.drag.start,b=this.drag.end||a;this.cancel();if(e.type==='pointercancel')return true;const width=Math.abs(b[0]-a[0])<5?280:Math.max(80,Math.abs(b[0]-a[0]));const n=s.canvas.createTextNode({pos:{x:Math.min(a[0],b[0]),y:Math.min(a[1],b[1])},size:{width,height:Math.abs(b[1]-a[1])<5?100:Math.max(45,Math.abs(b[1]-a[1]))},text:'',save:false,focus:false});n.unknownData.cdtText={...clone(s.plugin.settings.textStyle),autoFit:true};this.armed=false;this.createButton?.setAttribute('aria-pressed','false');n.attach();n.render();this.sync();s.canvas.selectOnly(n);n.startEditing();this.drafts.add(n);s.canvas.requestSave();this.selected=n;s.figures.panelRender();return true;}
 cancel(){this.armed=false;this.createButton?.setAttribute('aria-pressed','false');if(this.drag&&this.s.host.hasPointerCapture(this.drag.id))this.s.host.releasePointerCapture(this.drag.id);this.drag=null;this.ghost?.remove();this.ghost=null;}
 destroy(){for(const n of this.drafts)if(n.isEditing)n.blur();this.pruneDrafts();this.createButton?.remove();this.cancel();this.s.win.clearInterval(this.timer);for(const off of this.nodes.values())off();this.nodes.clear();}
}
module.exports={TextItems,defaults};


