'use strict';
const {Notice}=require('obsidian');
const {clone,upgrade}=require('./brush');
const W=require('./workspaces');
const {packMaterials,unpackMaterials}=require('./materials');
const labels={quick:'지정 도구 모음',brush:'브러시',eraser:'지우개',color:'색상',eyedropper:'스포이트',rectangle:'사각 선택',lasso:'올가미', 'move-layer':'오브젝트',shape:'도형',text:'텍스트',paper:'배경 용지'};
class WorkspaceUI{
 constructor(s){this.s=s;this.u=s.brushUI;const u=this.u;this.footer=s.element('div','cdt-workspace-footer',s.toolbar);s.button(this.footer,'chevrons-up-down','도구막대 접기 / 펼치기',()=>this.toggle('toolbarCollapsed'));s.button(this.footer,'panel-left','도구 속성 접기 / 펼치기',()=>this.toggle('contextCollapsed'));s.button(this.footer,'settings-2','도구막대 편집',()=>this.layout());s.button(this.footer,'library','소재 라이브러리',()=>u.materials.library());this.button=s.element('button','cdt-workspace-switch',this.footer);this.button.onclick=()=>this.open();s.tool=s.plugin.settings.lastTool||'brush';s.figures.panelRender();if(['brush','eraser'].includes(s.tool))u.render();this.applyLayout();}
 get settings(){return this.s.plugin.settings;}
 remember(){this.settings.lastTool=this.s.tool;this.s.plugin.saveData(this.settings);}
 toggle(key){this.settings[key]=!this.settings[key];for(const s of this.s.plugin.sessions.values())s.workspaceUI?.applyLayout();this.s.plugin.saveData(this.settings);}
 applyLayout(){const s=this.s,q=this.settings,buttons={brush:s.brushButton,eraser:s.eraserButton,color:s.colorButton,eyedropper:s.eyedropperButton,...s.editButtons,paper:s.paperButton,quick:s.quickTools?.button};for(const k of q.toolOrder){const b=buttons[k];if(b){s.tools.append(b);b.hidden=q.hiddenTools.includes(k);}}s.toolbar.style.width=(q.toolbarWidth||42)+'px';s.tools.hidden=!s.drawing||q.toolbarCollapsed;s.panel.style.left=s.figures.panel.style.left=((q.toolbarWidth||42)+24)+'px';s.panel.style.width=(q.contextWidth||242)+'px';if(!q.panelPositions?.layers)s.layers.style.width=(q.layerWidth||300)+'px';s.figures.panel.style.width=(q.contextWidth||242)+'px';s.panel.hidden=!s.drawing||q.contextCollapsed||!['brush','eraser'].includes(s.tool);s.figures.panel.hidden=q.contextCollapsed||!(s.drawing&&s.tool==='shape'||!s.drawing&&s.tool==='text'&&!s.textItems?.panelClosed);s.layers.hidden=!s.drawing||!!q.layersCollapsed;this.footer.hidden=!s.drawing;const w=q.workspaces.find(w=>w.id===q.workspaceId);this.button.textContent=w?.name||'작업環境';this.button.title='작업환경: '+w?.name;this.button.setAttribute('aria-label','작업환경: '+w?.name);s.toolbar.classList.toggle('cdt-toolbar-open',s.drawing);s.quickTools?.applyLayout();s.brushLayout?.apply();s.figureLayout?.apply();s.quickLayout?.apply();}
 settle(){for(const s of this.s.plugin.sessions.values()){s.figures?.confirm();s.selection?.confirm(false);s.selection?.end();s.finishStroke();for(const n of s.canvas.nodes.values())if(n.isEditing)n.blur();s.colorUI?.close();for(const m of [...s.brushUI.modals])m.close();}this.s.plugin.flush();}
 switchTo(id){const q=this.settings,w=q.workspaces.find(w=>w.id===id);if(!w||id===q.workspaceId)return;this.settle();W.captureCurrent(q);const state=clone(w.state);q.workspaceId=id;W.applyState(q,state);for(const s of this.s.plugin.sessions.values()){s.tool=q.lastTool;s.brushUI.group='전체';s.textItems?.cancel();if(['brush','eraser'].includes(s.tool))s.brushUI.render();s.refreshControls();s.workspaceUI?.applyLayout();s.scheduleRender();}this.s.plugin.saveData(q);new Notice('작업환경: '+w.name);}
 open(){const u=this.u,q=this.settings;W.captureCurrent(q);const m=u.modal('Drawing 작업환경','cdt-workspaces-dialog');const render=()=>{m.contentEl.replaceChildren();for(const w of q.workspaces){const row=u.el('div','cdt-workspace-row',m.contentEl);u.el('strong','',row,w.name+(w.id===q.workspaceId?' · 사용 중':''));u.btn(row,'전환',()=>{this.switchTo(w.id);m.close();});u.icon(row,'pencil',w.name+' 이름 변경',()=>u.nameDialog('작업환경 이름',w.name,name=>{w.name=name;this.save();render();}));u.icon(row,'copy',w.name+' 복제',()=>{W.captureCurrent(q);q.workspaces.push({...clone(w),id:crypto.randomUUID(),name:w.name+' 복사'});this.save();render();});u.icon(row,'trash-2',w.name+' 삭제',()=>{if(q.workspaces.length===1){new Notice('작업환경 하나는 남겨야 합니다.');return;}u.confirm('이 작업환경을 삭제할까요? Canvas 그림은 유지됩니다.',()=>{if(w.id===q.workspaceId)this.switchTo(q.workspaces.find(x=>x!==w).id);q.workspaces=q.workspaces.filter(x=>x!==w);this.save();render();});}).classList.add('cdt-danger');}
 const actions=u.el('div','cdt-row-actions',m.contentEl);u.btn(actions,'＋ 새 작업환경',()=>u.nameDialog('새 작업환경','새 작업환경',name=>{const fresh=upgrade({color:'#b6a0e2'});W.upgradeWorkspaces(fresh);q.workspaces.push({id:crypto.randomUUID(),name,state:W.capture(fresh)});this.save();render();}));u.btn(actions,'현재 환경 내보내기',()=>{W.captureCurrent(q);const w=q.workspaces.find(w=>w.id===q.workspaceId);this.download(w.name+'.drawing-workspace.json',{format:'canvas-drawing-workspace',version:1,workspace:w});});u.materials.fileInput(m.contentEl,'작업환경 가져오기','.json',f=>this.importFile(f,false,m.contentEl));u.el('p','cdt-hint',m.contentEl,'전환 전 설정은 자동 저장됩니다. 그림·레이어·Canvas 위치와 Drawing 켜짐 상태는 유지됩니다. 가져온 환경은 추가만 하며 자동 전환하지 않습니다.');u.btn(m.contentEl,'전체 설정 백업 / 복원',()=>this.backup());u.btn(m.contentEl,'닫기',()=>m.close());};render();}
 save(){this.s.plugin.saveData(this.settings);for(const s of this.s.plugin.sessions.values())s.workspaceUI?.applyLayout();}
 async download(name,data){try{const {dialog}=require('@electron/remote'),result=await dialog.showSaveDialog({title:'Drawing 설정 내보내기',defaultPath:name.replace(/[<>:"/\\|?*]/g,'_'),filters:[{name:'JSON',extensions:['json']}]});if(result.canceled||!result.filePath)return;require('node:fs').writeFileSync(result.filePath,JSON.stringify(packMaterials(data),null,2),'utf8');new Notice('설정을 내보냈습니다.');}catch(error){new Notice('내보내기 실패: '+error.message);}}
 async importFile(file,backup,parent){if(file.size>64*1024*1024)throw Error('64MB 이하 파일을 선택하세요.');const payload=unpackMaterials(JSON.parse(await file.text()));if(backup?payload.format!=='canvas-drawing-settings':payload.format!=='canvas-drawing-workspace')throw Error('선택한 가져오기 종류와 파일 형식이 다릅니다.');const {workspaces,report}=W.importWorkspaces(payload);this.settings.workspaces.push(...workspaces);if(backup&&payload.device){const d=payload.device;for(const[k,values]of Object.entries({inputMode:['automatic','pen','mouse'],penButton:['eraser','pan','none'],cursorMode:['both','tip','hotspot']}))if(values.includes(d[k]))this.settings[k]=d[k];if(typeof d.cursorPressure==='boolean')this.settings.cursorPressure=d.cursorPressure;}this.save();const text=`${workspaces.length}개 작업환경 추가 · ${report.length}개 항목 제외\n현재 작업환경 유지${backup?' · 장치 설정 복원':''}`;const result=this.u.el('div','cdt-import-result',parent,text);result.setAttribute('role','status');for(const line of report)this.u.el('p','cdt-hint',result,line);this.lastImport={loaded:workspaces.length,report};}
 backup(){const u=this.u,q=this.settings,m=u.modal('전체 설정 백업 / 복원');u.el('p','cdt-hint',m.contentEl,'작업환경·소재·장치 설정을 저장합니다. Canvas 그림은 포함하지 않습니다.\n복원은 작업환경을 목록에 추가하고 장치 설정을 복원합니다. 기존 환경과 현재 선택은 유지합니다.');u.btn(m.contentEl,'전체 설정 내보내기',()=>{W.captureCurrent(q);this.download('drawing-settings.json',{format:'canvas-drawing-settings',version:1,workspaces:q.workspaces,device:Object.fromEntries(['inputMode','penButton','cursorMode','cursorPressure'].map(k=>[k,q[k]]))});});u.materials.fileInput(m.contentEl,'전체 설정 복원 파일','.json',f=>{u.confirm('작업환경을 추가하고 장치 설정을 복원할까요?',()=>this.importFile(f,true,m.contentEl).catch(e=>new Notice(e.message)));});u.btn(m.contentEl,'닫기',()=>m.close());}
 layout(){const u=this.u,q=this.settings,m=u.modal('도구막대 편집');const render=()=>{m.contentEl.replaceChildren();q.toolOrder.forEach((key,i)=>{const row=u.el('div','cdt-workspace-row',m.contentEl);row.draggable=true;row.dataset.tool=key;row.ondragstart=e=>e.dataTransfer.setData('text/plain',key);row.ondragover=e=>{e.preventDefault();row.style.borderTop='2px solid var(--interactive-accent)';};row.ondragleave=()=>row.style.borderTop='';row.ondrop=e=>{e.preventDefault();const source=e.dataTransfer.getData('text/plain');if(source!==key&&q.toolOrder.includes(source)){q.toolOrder=q.toolOrder.filter(k=>k!==source);q.toolOrder.splice(q.toolOrder.indexOf(key),0,source);this.save();render();}};u.el('span','',row,labels[key]);const b=u.icon(row,q.hiddenTools.includes(key)?'eye-off':'eye',labels[key]+' 표시',()=>{if(key==='brush'){new Notice('브러시는 항상 표시합니다.');return;}q.hiddenTools=q.hiddenTools.includes(key)?q.hiddenTools.filter(k=>k!==key):[...q.hiddenTools,key];this.save();render();});b.setAttribute('aria-pressed',String(!q.hiddenTools.includes(key)));for(const [delta,icon]of [[-1,'chevron-up'],[1,'chevron-down']])u.icon(row,icon,labels[key]+(delta<0?' 위로':' 아래로'),()=>{const j=i+delta;if(j<0||j>=q.toolOrder.length)return;[q.toolOrder[i],q.toolOrder[j]]=[q.toolOrder[j],q.toolOrder[i]];this.save();render();});});for(const [key,label,min,max]of [['toolbarWidth','도구막대 폭',42,80],['contextWidth','도구 속성 폭',220,420],['layerWidth','레이어 폭',260,460]]){const row=u.el('label','cdt-select-row',m.contentEl,label),input=u.el('input','',row);input.type='range';input.min=min;input.max=max;input.value=q[key];input.setAttribute('aria-label',label);input.oninput=()=>{q[key]=Number(input.value);this.save();};}for(const[key,label]of [['brush','브러시 도구'],['eraser','지우개 도구'],['mix','색 혼합'],['drawing','드로잉 모드'],['color','색상 패널'],['layers','레이어 패널'],['swap','메인색 / 보조색 전환'],['transparent','투명색'],['selection','선택 방식 전환'],['shape','도형'],['move','누르는 동안 레이어 이동'],['quick','지정 도구 모음']]){const row=u.el('label','cdt-select-row',m.contentEl,label),i=u.el('input','',row);i.value=q.shortcuts[key];i.readOnly=true;i.setAttribute('aria-label',label);i.onclick=()=>require('./tool-shortcuts').shortcutDialog(this.s,'panel:'+key,label);}u.btn(m.contentEl,'닫기',()=>m.close());};render();}
 destroy(){this.footer.remove();}
}
module.exports={WorkspaceUI,upgradeWorkspaces:W.upgradeWorkspaces};
